import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n";

export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const{locale}=await params;if(!isLocale(locale))return{};const fr=locale==="fr";return{title:fr?"Pour les services de garde au Québec":"For childcare providers in Quebec",description:fr?"Créez ou revendiquez votre fiche MyCoco, présentez clairement votre service et préparez-vous à recevoir une demande locale mieux qualifiée.":"Create or claim your MyCoco listing, present your service clearly and prepare to receive better-qualified local demand."};}

export default async function ProvidersPage({params}:{params:Promise<{locale:string}>}){
  const{locale}=await params;if(!isLocale(locale))notFound();const fr=locale==="fr";
  const steps=fr?[["01","Créez ou revendiquez votre fiche","Nom, type de garde, secteur : vous partez d’une présence claire et vérifiable."],["02","Complétez ce que les familles veulent savoir","Horaires, âges accueillis, services, coordonnées et, lorsque disponible, vos places déclarées."],["03","Soyez trouvé au bon moment","Votre fiche apparaît dans l’annuaire local et dans les parcours de recherche pertinents."],["04","Transformez la demande en valeur","MyCoco pourra ensuite vous aider à suivre les demandes, mesurer la demande locale et convertir plus efficacement."]]:[["01","Create or claim your listing","Name, care type and area: start from a clear, verifiable presence."],["02","Complete what families need to know","Hours, age groups, services, contact details and, when available, declared openings."],["03","Get found at the right time","Your profile appears in local discovery and relevant family journeys."],["04","Turn demand into value","MyCoco can then help track demand, understand your market and convert more effectively."]];
  return <main>
    <section className="mc-content-hero"><div className="mc-shell"><span className="mc-kicker">{fr?"MYCOCO POUR LES SERVICES DE GARDE":"MYCOCO FOR CHILDCARE PROVIDERS"}</span><h1 className="mc-display">{fr?"Votre prochaine famille ne devrait pas vous trouver par hasard.":"Your next family should not find you by accident."}</h1><p className="mc-lead">{fr?"MyCoco construit une marketplace où les familles commencent par leur besoin et où les services contrôlent leur présence. Le but n’est pas de vous vendre du trafic : c’est de rendre votre offre visible au moment où une vraie demande locale existe.":"MyCoco is building a marketplace where families start from their needs and providers control their presence. The goal is not to sell traffic, but to surface your offer when real local demand exists."}</p><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:26}}><Link className="mc-btn mc-btn-primary" href={`/${locale}/inscription?role=provider`}>{fr?"Créer mon espace service":"Create my provider space"} →</Link><Link className="mc-btn mc-btn-outline" href={`/${locale}/garderies`}>{fr?"Voir l’expérience famille":"See the family experience"}</Link></div><p style={{fontSize:11,color:"#707887",marginTop:12}}>{fr?"Création gratuite au lancement · aucun abonnement nécessaire pour créer votre présence de base":"Free to create at launch · no subscription required for a basic presence"}</p></div></section>

    <section className="mc-content-body"><div className="mc-shell"><span className="mc-kicker">{fr?"LE MODÈLE":"THE MODEL"}</span><h2 className="mc-h2">{fr?"Une fiche publique aujourd’hui. Un moteur de demande demain.":"A public profile today. A demand engine tomorrow."}</h2><div className="mc-split"><div className="mc-panel soft-coral"><small className="mc-kicker">{fr?"CE QUE VOUS CONTRÔLEZ":"WHAT YOU CONTROL"}</small><h2>{fr?"Votre présence MyCoco":"Your MyCoco presence"}</h2><p>{fr?"Une fiche de répertoire peut exister à partir de données publiques. En créant votre espace, vous pourrez contrôler les informations que vous fournissez directement et distinguer clairement ce qui vient de vous de ce qui provient du répertoire.":"A directory listing can exist from public data. By creating your space, you can control the information you provide directly and clearly separate it from directory data."}</p><div className="mc-process">{steps.slice(0,2).map(([n,t,d])=><div key={n}><b>{n}</b><div><strong>{t}</strong><small>{d}</small></div></div>)}</div></div><div className="mc-panel soft-aqua"><small className="mc-kicker">{fr?"CE QUE MYCOCO CONSTRUIT":"WHAT MYCOCO BUILDS"}</small><h2>{fr?"De la visibilité à la demande qualifiée":"From visibility to qualified demand"}</h2><p>{fr?"À mesure que la densité locale augmente, MyCoco peut mesurer les besoins par secteur, âge, type de garde et échéance. C’est cette donnée de demande — pas un simple nombre de clics — qui peut devenir votre vraie valeur commerciale.":"As local density grows, MyCoco can measure needs by area, age, care type and timing. That demand data — not raw clicks — is the real commercial value."}</p><div className="mc-process">{steps.slice(2).map(([n,t,d])=><div key={n}><b>{n}</b><div><strong>{t}</strong><small>{d}</small></div></div>)}</div></div></div></div></section>

    <section className="mc-dark-section"><div className="mc-shell"><span className="mc-kicker">{fr?"COMPLÉMENTAIRE AU QUÉBEC":"BUILT AROUND QUEBEC"}</span><h2 className="mc-h2">{fr?"MyCoco ne remplace pas vos obligations d’admission. Il améliore la découverte et la relation en amont.":"MyCoco does not replace admission obligations. It improves discovery and the relationship before them."}</h2><p className="mc-lead">{fr?"Lorsque le Portail d’inscription aux services de garde ou d’autres démarches officielles s’appliquent, elles continuent de s’appliquer. MyCoco se positionne sur la visibilité, la comparaison, la qualité des informations et, progressivement, la gestion de la demande.":"Where Quebec’s childcare registration portal or other official processes apply, they continue to apply. MyCoco focuses on visibility, comparison, information quality and, progressively, demand management."}</p><Link className="mc-btn mc-btn-primary" href={`/${locale}/inscription?role=provider`} style={{marginTop:22}}>{fr?"Créer mon espace — gratuit":"Create my space — free"} →</Link></div></section>
  </main>;
}
