import { notFound } from "next/navigation";
import Link from "next/link";
import { isLocale } from "@/lib/i18n";
import { getCurrentFamily } from "@/lib/family-auth";

export default async function FamilyProfilePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale }=await params;if(!isLocale(locale))notFound();const fr=locale==='fr';const family=await getCurrentFamily();
  if(!family) return <main className="mcs-profile-auth"><span>MYCOCO</span><h1>{fr?"Connectez-vous pour accéder à votre profil.":"Sign in to access your profile."}</h1><Link href={`/${locale}/connexion?role=family`}>{fr?"Se connecter":"Sign in"}</Link><style>{`.mcs-profile-auth{--blue:#333873;--yellow:#ffd44f;min-height:68vh;display:grid;place-items:center;align-content:center;text-align:center;gap:11px;background:#f7f7fb;color:#2b2d42;padding:30px;font-family:Arial,Helvetica,sans-serif}.mcs-profile-auth>span{color:#898b9a;font-size:9px;font-weight:900;letter-spacing:.1em}.mcs-profile-auth h1{max-width:650px;margin:0;color:var(--blue);font-size:42px;letter-spacing:-.045em}.mcs-profile-auth a{display:inline-flex;margin-top:5px;padding:11px 14px;border-radius:8px;background:var(--yellow);color:var(--blue);font-size:10px;font-weight:900}`}</style></main>;

  return <main className="mcs-profile-page"><div className="mcs-profile-wrap">
    <Link className="mcs-profile-back" href={`/${locale}/espace-famille`}>← {fr?"Mon espace famille":"My family space"}</Link>
    <div className="mcs-profile-head"><span>{fr?"PROFIL FAMILLE":"FAMILY PROFILE"}</span><h1>{fr?"Gardez uniquement les informations qui rendent MyCoco plus utile.":"Keep only the information that makes MyCoco more useful."}</h1><p>{fr?"Votre profil sert à éviter de ressaisir les mêmes informations et à améliorer vos recherches. Il n’est jamais affiché comme une fiche publique dans l’annuaire des services de garde.":"Your profile avoids repeated data entry and improves searches. It is never displayed as a public listing in the childcare directory."}</p></div>

    <div className="mcs-profile-layout"><form className="mcs-profile-card" action="/api/famille/profil" method="post"><input type="hidden" name="locale" value={locale}/><div className="mcs-profile-card-head"><b>{fr?"Informations de base":"Basic information"}</b><small>{fr?"Privées":"Private"}</small></div><label><span>{fr?"Prénom":"First name"}</span><input name="firstName" value={family.first_name||""} readOnly /></label><label><span>{fr?"Adresse courriel":"Email address"}</span><input value={family.email||""} readOnly /></label><label><span>{fr?"Ville ou code postal":"City or postal code"}</span><input name="cityOrPostal" defaultValue={family.city_or_postal||""} placeholder={fr?"Ex. Mirabel, J7J 1A1":"e.g. Mirabel, J7J 1A1"}/></label><div className="mcs-profile-note"><strong>{fr?"Pourquoi demander votre secteur ?":"Why ask for your area?"}</strong><p>{fr?"Uniquement pour rapprocher les recherches de votre quotidien et éviter de repartir de zéro. Vous pourrez toujours modifier ce champ.":"Only to keep searches relevant to daily life and avoid starting over. You can change it at any time."}</p></div><button type="submit">{fr?"Enregistrer les modifications":"Save changes"}</button></form>

    <aside className="mcs-profile-side"><section><span>{fr?"CONFIDENTIALITÉ":"PRIVACY"}</span><h2>{fr?"Votre famille n’est pas un profil public.":"Your family is not a public profile."}</h2><p>{fr?"Les coordonnées et informations familiales restent séparées des fiches de services de garde. MyCoco n’a pas besoin du nom complet ni de la date de naissance exacte de votre enfant pour faire le matching initial.":"Contact and family information stays separate from childcare listings. MyCoco does not need your child’s full name or exact birth date for initial matching."}</p></section><section><span>{fr?"PROCHAINE ÉVOLUTION":"NEXT"}</span><h2>{fr?"Plusieurs enfants, sans surcharger l’expérience.":"Multiple children, without clutter."}</h2><p>{fr?"L’espace pourra enregistrer plusieurs enfants, leurs tranches d’âge et des préférences utiles lorsque cette fonction apporte une vraie valeur au matching et aux alertes.":"The space can later support multiple children, age ranges and useful preferences when that adds real value to matching and alerts."}</p></section></aside></div>
  </div>
  <style>{`
    .mcs-profile-page{--blue:#333873;--blue-dark:#242954;--yellow:#ffd44f;--bg:#f7f7fb;--line:#e1e2ea;--muted:#737587;min-height:calc(100vh - 72px);background:var(--bg);color:#2b2d42;padding:44px 20px 82px;font-family:Arial,Helvetica,sans-serif}.mcs-profile-wrap{width:min(980px,100%);margin:auto}.mcs-profile-back{color:#77798a;font-size:10px;font-weight:850}.mcs-profile-head{max-width:800px;margin-top:42px}.mcs-profile-head>span,.mcs-profile-side section>span{color:#888a99;font-size:9px;font-weight:900;letter-spacing:.1em}.mcs-profile-head h1{margin:11px 0 16px;color:var(--blue);font-size:clamp(42px,5.7vw,65px);line-height:.98;letter-spacing:-.05em}.mcs-profile-head p{max-width:720px;margin:0;color:var(--muted);font-size:14px;line-height:1.65}.mcs-profile-layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:22px;margin-top:32px;align-items:start}.mcs-profile-card{padding:24px;background:#fff;border:1px solid var(--line);border-radius:14px}.mcs-profile-card-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:19px;padding-bottom:13px;border-bottom:1px solid #ececf1}.mcs-profile-card-head b{color:var(--blue);font-size:12px}.mcs-profile-card-head small{padding:5px 7px;border-radius:999px;background:#f0edff;color:var(--blue);font-size:7px;font-weight:900}.mcs-profile-card label{display:grid;gap:6px;margin-bottom:14px}.mcs-profile-card label span{color:#5e6070;font-size:9px;font-weight:850}.mcs-profile-card input{height:46px;border:1px solid #d8d9e3;border-radius:8px;padding:0 11px;background:#fff;color:#2b2d42;outline:none}.mcs-profile-card input:focus{border-color:var(--blue);box-shadow:0 0 0 3px rgba(51,56,115,.08)}.mcs-profile-card input[readonly]{color:#858797;background:#f5f5f8}.mcs-profile-note{padding:13px;border-radius:9px;background:#fff7d7;margin:17px 0}.mcs-profile-note strong{color:var(--blue);font-size:9px}.mcs-profile-note p{margin:4px 0 0;color:#706d61;font-size:9px;line-height:1.5}.mcs-profile-card button{width:100%;height:46px;border:0;border-radius:8px;background:var(--yellow);color:var(--blue-dark);font-size:10px;font-weight:900;cursor:pointer}.mcs-profile-side{display:grid;gap:11px}.mcs-profile-side section{padding:18px;border:1px solid var(--line);border-radius:13px;background:#fff}.mcs-profile-side section:last-child{background:#f0edff}.mcs-profile-side h2{margin:8px 0 7px;color:var(--blue);font-size:20px;line-height:1.1;letter-spacing:-.03em}.mcs-profile-side p{margin:0;color:var(--muted);font-size:9px;line-height:1.6}@media(max-width:800px){.mcs-profile-layout{grid-template-columns:1fr}}@media(max-width:520px){.mcs-profile-page{padding-left:14px;padding-right:14px}.mcs-profile-head h1{font-size:42px}}
  `}</style></main>;
}
