import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n";

export default async function FamilySpacePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const fr = locale === "fr";
  return <main className="mc-family-space">
    <section className="mc-family-hero"><div className="mc-family-wrap">
      <span className="mc-family-eyebrow">MYCOCO · {fr ? "ESPACE FAMILLE" : "FAMILY SPACE"}</span>
      <div className="mc-family-grid">
        <div><h1>{fr ? "Votre recherche commence ici. Votre espace la fait continuer." : "Your search starts here. Your space keeps it moving."}</h1><p>{fr ? "Créez votre espace famille pour enregistrer vos enfants, vos critères, vos recherches et recevoir les nouvelles solutions qui peuvent correspondre." : "Create your family space to save your children, criteria and searches, and hear about new options that may fit."}</p><Link className="mc-family-primary" href={`/${locale}/mon-besoin`}>{fr ? "Commencer ma recherche" : "Start my search"} <span>→</span></Link><small>{fr ? "Vous pouvez chercher sans compte. L'espace devient utile lorsque vous souhaitez conserver votre recherche." : "You can search without an account. Your space becomes useful when you want to save your search."}</small></div>
        <div className="mc-family-preview"><span>{fr ? "VOTRE ESPACE" : "YOUR SPACE"}</span><strong>{fr ? "Une seule place pour votre recherche familiale." : "One place for your family's childcare journey."}</strong><div><b>01</b><span>{fr ? "Ma famille" : "My family"}</span></div><div><b>02</b><span>{fr ? "Mes recherches" : "My searches"}</span></div><div><b>03</b><span>{fr ? "Mes alertes" : "My alerts"}</span></div><div><b>04</b><span>{fr ? "Mes favoris" : "My favorites"}</span></div></div>
      </div>
    </div></section>
    <section className="mc-family-body"><div className="mc-family-wrap"><div className="mc-family-heading"><span>{fr ? "POURQUOI CRÉER UN ESPACE ?" : "WHY CREATE A SPACE?"}</span><h2>{fr ? "Pas pour remplir un formulaire. Pour ne plus recommencer." : "Not to fill out a form. So you don't have to start over."}</h2></div><div className="mc-family-cards">
      {[["01",fr?"Votre famille":"Your family",fr?"Enfants, âges et préférences conservés au même endroit.":"Children, ages and preferences kept in one place."],["02",fr?"Vos recherches":"Your searches",fr?"Plusieurs besoins peuvent rester actifs : maintenant, plus tard ou en secours.":"Keep several needs active: now, later or backup."],["03",fr?"Vos alertes":"Your alerts",fr?"Recevez les nouvelles possibilités pertinentes au lieu de recommencer vos recherches.":"Get relevant new possibilities instead of starting your search again."],["04",fr?"Votre historique":"Your history",fr?"Retrouvez les services consultés, favoris et contacts lorsque vous revenez.":"Find viewed services, favorites and contacts when you come back."]].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}
    </div><div className="mc-family-bridge"><div><span>{fr ? "LE BON PARCOURS" : "THE RIGHT JOURNEY"}</span><strong>{fr ? "1. Chercher · 2. Trouver · 3. Enregistrer · 4. Suivre" : "1. Search · 2. Discover · 3. Save · 4. Follow"}</strong></div><Link href={`/${locale}/mon-besoin`}>{fr ? "Définir mon besoin" : "Define my need"} →</Link></div></div></section>
    <style>{`.mc-family-space{background:#fbfaf7;color:#18352c}.mc-family-wrap{width:min(1160px,calc(100% - 40px));margin:auto}.mc-family-hero{padding:72px 0 84px;background:radial-gradient(circle at 80% 20%,#dceee4,transparent 35%),linear-gradient(135deg,#f5f0e7,#edf5ef);border-bottom:1px solid #dfe7e2}.mc-family-eyebrow,.mc-family-heading>span{font-size:10px;font-weight:950;letter-spacing:.14em;color:#4b7b66}.mc-family-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:80px;align-items:center;margin-top:17px}.mc-family-grid h1{font-size:clamp(45px,6vw,75px);line-height:.96;letter-spacing:-.068em;margin:0 0 22px}.mc-family-grid p{max-width:700px;color:#63736b;font-size:18px;line-height:1.6}.mc-family-primary{display:inline-flex;gap:9px;margin-top:14px;padding:15px 20px;border-radius:12px;background:#18352c;color:#fff;font-size:13px;font-weight:900}.mc-family-grid small{display:block;max-width:540px;color:#7c8983;font-size:10px;line-height:1.5;margin-top:12px}.mc-family-preview{padding:26px;background:#fff;border:1px solid #dfe7e2;border-radius:24px;box-shadow:0 24px 60px rgba(24,53,44,.1)}.mc-family-preview>span{font-size:9px;font-weight:950;letter-spacing:.14em;color:#789087}.mc-family-preview>strong{display:block;font-size:22px;line-height:1.08;letter-spacing:-.04em;margin:18px 0}.mc-family-preview>div{display:flex;align-items:center;gap:12px;padding:13px 0;border-top:1px solid #e7ece8}.mc-family-preview b{font-size:9px;color:#c47745}.mc-family-preview span:not(:first-child){font-size:12px;font-weight:800}.mc-family-body{padding:82px 0}.mc-family-heading{max-width:760px}.mc-family-heading h2{font-size:clamp(32px,4vw,52px);line-height:1;letter-spacing:-.05em;margin:12px 0 35px}.mc-family-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.mc-family-cards article{padding:24px;background:#fff;border:1px solid #dfe7e2;border-radius:19px}.mc-family-cards b{font-size:10px;color:#c47745}.mc-family-cards h3{font-size:20px;letter-spacing:-.035em;margin:30px 0 9px}.mc-family-cards p{color:#718079;font-size:12px;line-height:1.6;margin:0}.mc-family-bridge{margin-top:26px;padding:24px;border-radius:19px;background:#18352c;color:#fff;display:flex;justify-content:space-between;align-items:center;gap:20px}.mc-family-bridge span{display:block;font-size:9px;font-weight:950;letter-spacing:.14em;color:#a9c9b8}.mc-family-bridge strong{display:block;font-size:15px;margin-top:8px}.mc-family-bridge a{padding:12px 15px;border-radius:10px;background:#fff;color:#18352c;font-size:11px;font-weight:900;white-space:nowrap}@media(max-width:900px){.mc-family-grid{grid-template-columns:1fr;gap:35px}.mc-family-cards{grid-template-columns:1fr 1fr}}@media(max-width:560px){.mc-family-hero{padding:52px 0 60px}.mc-family-cards{grid-template-columns:1fr}.mc-family-bridge{flex-direction:column;align-items:flex-start}}
    `}</style>
  </main>;
}
