import type { Metadata } from "next";
import Link from "next/link";
import { getChildcareData, matchReasons, normalize, rankChildcare, typeLabel } from "@/lib/childcare";

export const dynamic="force-dynamic";

export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const{locale}=await params;const fr=locale!=="en";return{title:fr?"Garderies, CPE et milieux familiaux au Québec":"Daycares, CPEs and home childcare in Quebec",description:fr?"Recherchez et comparez les services de garde selon votre ville, l’âge de votre enfant et votre type de garde. Les disponibilités restent clairement identifiées comme à confirmer.":"Search and compare childcare by city, child age and care type. Availability is clearly identified as requiring confirmation."};}

export default async function GarderiesPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const{locale}=await params;const q=await searchParams;const fr=locale!=="en";const data=await getChildcareData();const query=typeof q.ville==="string"?q.ville:"";const type=typeof q.type==="string"?q.type:"";const age=typeof q.age==="string"?q.age:"";const debut=typeof q.debut==="string"?q.debut:"";const demandId=typeof q.demandeId==="string"?q.demandeId:"";const n=normalize(query);
  const filtered=data.records.filter(record=>{if(!n)return true;const city=normalize(record.city);const postal=normalize(record.postalCode).replace(/\s+/g,"");const needle=n.replace(/\s+/g,"");return city.includes(n)||postal.includes(needle)});const ranked=rankChildcare(filtered,query,type,undefined,undefined,age);const hasNeed=Boolean(query||type||age||debut);
  return <main className="mc-directory-page">
    <section className="mc-directory-hero"><div className="mc-shell"><div className="mc-breadcrumb"><Link href={`/${locale}`}>MyCoco</Link><span>›</span><span>{fr?"Annuaire des services de garde":"Childcare directory"}</span></div><div className="mc-directory-hero-grid"><div><span className="mc-kicker">{fr?"ANNUAIRE MYCOCO · QUÉBEC":"MYCOCO DIRECTORY · QUEBEC"}</span><h1 className="mc-display">{fr?"Cherchez moins. Comparez ce qui compte.":"Search less. Compare what matters."}</h1><p className="mc-lead">{fr?"CPE, garderies et milieux familiaux : explorez l’offre répertoriée, puis utilisez vos critères pour prioriser les fiches à examiner. Une fiche n’est jamais présentée comme une place disponible.":"CPEs, daycares and home childcare: explore listed supply, then use your criteria to prioritize profiles worth reviewing. A listing is never presented as an available spot."}</p></div><div className="mc-directory-side"><span>{fr?"VOUS VOULEZ UN RÉSULTAT ADAPTÉ ?":"WANT A TAILORED RESULT?"}</span><strong>{fr?"Partez de votre famille, pas de la liste.":"Start from your family, not the list."}</strong><span>{fr?"4 questions · sans compte pour commencer":"4 questions · no account to start"}</span><Link href={`/${locale}/mon-besoin`}>{fr?"Lancer mon matching":"Start my matching"}<b>→</b></Link></div></div></div></section>
    <section className="mc-directory-body"><div className="mc-shell">
      <form className="mc-directory-filters" method="get"><label><span>{fr?"VILLE OU CODE POSTAL":"CITY OR POSTAL CODE"}</span><input name="ville" defaultValue={query} placeholder={fr?"Ex. Mirabel ou J7J 1A1":"e.g. Mirabel or J7J 1A1"}/></label><label><span>{fr?"ÂGE":"AGE"}</span><select name="age" defaultValue={age}><option value="">{fr?"Tous les âges":"All ages"}</option><option value="0-18">0–18 {fr?"mois":"months"}</option><option value="18-36">18–36 {fr?"mois":"months"}</option><option value="3-5">3–5 {fr?"ans":"years"}</option><option value="5+">5+ {fr?"ans":"years"}</option></select></label><label><span>{fr?"TYPE DE GARDE":"CARE TYPE"}</span><select name="type" defaultValue={type}><option value="">{fr?"Tous les services":"All providers"}</option><option value="cpe">CPE</option><option value="subventionnee">{fr?"Garderie subventionnée":"Subsidized daycare"}</option><option value="milieu familial">{fr?"Milieu familial":"Home childcare"}</option><option value="non subventionnee">{fr?"Garderie non subventionnée":"Non-subsidized daycare"}</option></select></label><button>{fr?"Rechercher":"Search"} →</button></form>
      {hasNeed&&<div style={{display:"flex",gap:7,flexWrap:"wrap",alignItems:"center",marginTop:13,fontSize:9}}><b style={{color:"#d9584d"}}>{fr?"VOTRE RECHERCHE":"YOUR SEARCH"}</b>{query&&<span style={{padding:"6px 8px",background:"#e9f9f6",borderRadius:999}}>{query}</span>}{age&&<span style={{padding:"6px 8px",background:"#e9f9f6",borderRadius:999}}>{age}</span>}{type&&<span style={{padding:"6px 8px",background:"#e9f9f6",borderRadius:999}}>{typeLabel(type,fr)}</span>}<Link href={`/${locale}/mon-besoin`} style={{marginLeft:"auto",fontWeight:900,color:"#d9584d"}}>{fr?"Affiner avec MyCoco":"Refine with MyCoco"} →</Link></div>}
      <div className="mc-results-head"><div><span className="mc-kicker">{fr?"RÉSULTATS":"RESULTS"}</span><h2>{ranked.length} {fr?(ranked.length===1?"service à explorer":"services à explorer"):(ranked.length===1?"provider to explore":"providers to explore")}</h2></div><p style={{maxWidth:350,color:"#727987",fontSize:9,lineHeight:1.55}}>✓ {fr?"MyCoco n’invente ni avis, ni prix, ni photo, ni disponibilité.":"MyCoco does not invent reviews, prices, photos or availability."}</p></div>
      {ranked.length===0?<div className="mc-panel" style={{textAlign:"center",padding:50}}><h2>{fr?"Aucun résultat avec ces critères.":"No result with these filters."}</h2><p>{fr?"Élargissez votre secteur ou laissez MyCoco repartir de votre besoin.":"Broaden your area or let MyCoco restart from your need."}</p><Link className="mc-btn mc-btn-primary" href={`/${locale}/mon-besoin`}>{fr?"Décrire mon besoin":"Describe my need"} →</Link></div>:<div className="mc-provider-grid14">{ranked.slice(0,30).map((record,index)=>{const reasons=matchReasons(record,query,type,fr,age);let href=`/${locale}/garderie/${record.slug}`;if(demandId)href+=`?demandeId=${encodeURIComponent(demandId)}`;return <Link className="mc-provider-card14" href={href} key={record.id}><div className="mc-provider-visual14"><b>{record.name.slice(0,1).toUpperCase()}</b><span>{typeLabel(record.type,fr)}</span></div><div className="mc-provider-body14"><small>{record.city}{record.postalCode?` · ${record.postalCode}`:""}</small><h3>{record.name}</h3>{reasons.length?<div style={{display:"flex",gap:5,flexWrap:"wrap",minHeight:25}}>{reasons.slice(0,3).map(reason=><span key={reason} style={{padding:"5px 7px",borderRadius:999,background:"#e9f9f6",color:"#33786f",fontSize:7,fontWeight:850}}>✓ {reason}</span>)}</div>:<p>{fr?"Informations publiques disponibles dans la fiche.":"Public information available in profile."}</p>}<footer><span>{fr?"Disponibilité à confirmer":"Availability to confirm"}</span><strong>{fr?"Voir la fiche":"View profile"} →</strong></footer></div></Link>})}</div>}
      <div className="mc-data-note"><span>i</span><p><strong>{fr?"Répertoire ≠ disponibilité":"Directory ≠ availability"}</strong><br/>{fr?`MyCoco aide à découvrir et comparer. L’admission et la disponibilité doivent être confirmées auprès du service et, lorsque requis, via les démarches officielles du Québec. Données : ${data.updatedAt||"date non disponible"}.`:`MyCoco helps families discover and compare. Admission and availability must be confirmed with the provider and, when required, through Quebec’s official process. Data: ${data.updatedAt||"date unavailable"}.`}</p></div>
    </div></section>
  </main>;
}
