import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { cities } from "@/lib/site";
import { getChildcareData, typeLabel } from "@/lib/childcare";
import { isLocale, locales, type Locale } from "@/lib/i18n";

export function generateStaticParams(){return locales.flatMap(locale=>cities.map(city=>({locale,city:city.slug})))}
export async function generateMetadata({params}:{params:Promise<{locale:string;city:string}>}):Promise<Metadata>{const{locale:raw,city:slug}=await params;if(!isLocale(raw))return{};const city=cities.find(item=>item.slug===slug);if(!city)return{};const fr=raw==="fr";const title=fr?`Garderies à ${city.name} : CPE, garderies et milieux familiaux`:`Daycares in ${city.name}: CPEs, daycares and home childcare`;const description=fr?`Comparez les services de garde répertoriés à ${city.name} et lancez un matching MyCoco selon l’âge de votre enfant et vos besoins.`:`Compare listed childcare in ${city.name} and start a MyCoco match based on your child’s age and needs.`;return{title,description,alternates:{canonical:`/${raw}/garderies/${city.slug}`,languages:{"fr-CA":`/fr/garderies/${city.slug}`,"en-CA":`/en/garderies/${city.slug}`}},openGraph:{title,description,type:"website",siteName:"MyCoco"}}}

export default async function CityChildcarePage({params}:{params:Promise<{locale:string;city:string}>}){const{locale:raw,city:slug}=await params;if(!isLocale(raw))notFound();const city=cities.find(item=>item.slug===slug);if(!city)notFound();const locale=raw as Locale;const fr=locale==="fr";const data=await getChildcareData();const providers=data.records.filter(record=>record.city.toLowerCase().trim()===city.name.toLowerCase().trim());const counts=providers.reduce<Record<string,number>>((acc,record)=>{const label=typeLabel(record.type,fr);acc[label]=(acc[label]||0)+1;return acc},{});const jsonLd={"@context":"https://schema.org","@type":"CollectionPage",name:fr?`Services de garde à ${city.name}`:`Childcare in ${city.name}`,description:fr?`Annuaire MyCoco des solutions de garde à ${city.name}.`:`MyCoco directory of childcare in ${city.name}.`,url:`/${locale}/garderies/${city.slug}`,isPartOf:{"@type":"WebSite",name:"MyCoco"}};return <main className="mc-directory-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
<section className="mc-directory-hero"><div className="mc-shell"><div className="mc-breadcrumb"><Link href={`/${locale}/garderies`}>{fr?"Annuaire":"Directory"}</Link><span>›</span><span>{city.name}</span></div><span className="mc-kicker">{fr?"GARDE D’ENFANTS · RECHERCHE LOCALE":"CHILDCARE · LOCAL SEARCH"}</span><h1 className="mc-display">{fr?`Trouver une garderie à ${city.name}, sans ouvrir 30 onglets.`:`Find childcare in ${city.name} without opening 30 tabs.`}</h1><p className="mc-lead">{fr?`${providers.length} service${providers.length===1?"":"s"} répertorié${providers.length===1?"":"s"} dans le secteur. Parcourez l’offre locale, puis laissez MyCoco vous aider à prioriser les options selon votre famille.`:`${providers.length} listed provider${providers.length===1?"":"s"} in this area. Browse locally, then let MyCoco prioritize options around your family.`}</p><div style={{display:"flex",gap:9,flexWrap:"wrap",marginTop:24}}><Link className="mc-btn mc-btn-primary" href={`/${locale}/mon-besoin?ville=${encodeURIComponent(city.name)}`}>{fr?"Trouver les meilleures options pour moi":"Find my best options"} →</Link><Link className="mc-btn mc-btn-outline" href={`/${locale}/garderies?ville=${encodeURIComponent(city.name)}`}>{fr?"Filtrer l’annuaire":"Filter directory"}</Link></div></div></section>
<section className="mc-directory-body"><div className="mc-shell"><div className="mc-split"><div className="mc-panel" style={{background:"#17233b",color:"#fff"}}><span className="mc-kicker">{fr?"OFFRE LOCALE":"LOCAL SUPPLY"}</span><div style={{fontSize:62,fontWeight:950,letterSpacing:"-.06em",lineHeight:1,marginTop:12}}>{providers.length}</div><p style={{color:"#c3cad6"}}>{fr?`services répertoriés à ${city.name}`:`listed providers in ${city.name}`}</p></div><div className="mc-panel soft-aqua"><span className="mc-kicker">{fr?"RÉPARTITION":"BREAKDOWN"}</span><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:9,marginTop:15}}>{Object.entries(counts).map(([label,count])=><div key={label} style={{padding:12,background:"#fff",borderRadius:11}}><strong style={{display:"block",fontSize:21}}>{count}</strong><span style={{fontSize:9,color:"#737b88"}}>{label}</span></div>)}</div></div></div>
<div style={{margin:"65px 0 28px"}}><span className="mc-kicker">MYCOCO MATCH</span><h2 className="mc-h2">{fr?"Un annuaire pour explorer. Un matching pour décider.":"A directory to explore. Matching to decide."}</h2><p className="mc-lead">{fr?"La proximité seule ne suffit pas. L’âge, le type de garde et le moment recherché changent les options à examiner en priorité.":"Proximity alone is not enough. Age, care type and timing change which options deserve attention first."}</p></div>
<div className="mc-results-head"><div><span className="mc-kicker">{fr?`SERVICES À ${city.name.toUpperCase()}`:`PROVIDERS IN ${city.name.toUpperCase()}`}</span><h2>{fr?"Explorez l’offre locale":"Explore local care"}</h2></div><p style={{maxWidth:320,color:"#747b87",fontSize:9}}>✓ {fr?"Une fiche répertoriée n’indique pas qu’une place est disponible.":"A listed profile does not mean a spot is available."}</p></div>
{providers.length?<div className="mc-provider-grid14">{providers.slice(0,24).map(record=><Link className="mc-provider-card14" key={record.id} href={`/${locale}/garderie/${record.slug}`}><div className="mc-provider-visual14"><b>{record.name.slice(0,1).toUpperCase()}</b><span>{typeLabel(record.type,fr)}</span></div><div className="mc-provider-body14"><small>{record.postalCode||city.name}</small><h3>{record.name}</h3><p>{record.capacityTotal?(fr?`Capacité déclarée : ${record.capacityTotal}`:`Declared capacity: ${record.capacityTotal}`):(fr?"Capacité à confirmer":"Capacity to confirm")}</p><footer><span>{fr?"Disponibilité à confirmer":"Availability to confirm"}</span><strong>{fr?"Voir la fiche":"View profile"} →</strong></footer></div></Link>)}</div>:<div className="mc-panel" style={{textAlign:"center"}}><h2>{fr?"Aucun service répertorié dans ce secteur.":"No listed provider in this area."}</h2><p>{fr?"Élargissez la zone ou lancez une recherche MyCoco.":"Broaden the area or start a MyCoco search."}</p></div>}
<div className="mc-data-note"><span>i</span><p><strong>{fr?"Données de répertoire, pas promesse de place.":"Directory data, not a spot promise."}</strong><br/>{fr?`MyCoco distingue les services répertoriés de la disponibilité réelle. L’admission doit être confirmée selon les démarches applicables au Québec. Données : ${data.updatedAt||"date non disponible"}.`:`MyCoco separates listed providers from actual availability. Admission must be confirmed through applicable Quebec processes. Data: ${data.updatedAt||"date unavailable"}.`}</p></div>
</div></section></main>}
