"use client";

import { useEffect } from "react";
import { analyticsConsentGiven } from "./CookieConsent";

const UTM_KEYS = ["utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content"] as const;
type FunnelEvent = { event: "page_view" | "cta_click" | "form_start" | "step_complete" | "demand_submitted" | "results_view" | "provider_click"; path: string; locale?: "fr" | "en"; step?: number; source?: string; providerId?: string };

function persistAttribution(){try{const p=new URLSearchParams(window.location.search);for(const key of UTM_KEYS){const value=p.get(key);if(value&&analyticsConsentGiven())window.localStorage.setItem(`mycoco_${key}`,value.slice(0,120));}}catch{}}
function attribution(){try{return UTM_KEYS.map(key=>{const value=window.localStorage.getItem(`mycoco_${key}`);return value?`${key}=${encodeURIComponent(value)}`:""}).filter(Boolean).join("&").slice(0,450)}catch{return ""}}
function sessionId(){try{const key="mycoco_session_id";let id=window.localStorage.getItem(key);if(!id){id=crypto.randomUUID();window.localStorage.setItem(key,id)}return id}catch{return "anonymous-session"}}
function send(event:FunnelEvent){if(!analyticsConsentGiven())return;const payload=JSON.stringify({...event,sessionId:sessionId(),source:event.source||attribution()||undefined});try{if(navigator.sendBeacon){navigator.sendBeacon("/api/events",new Blob([payload],{type:"application/json"}));return}void fetch("/api/events",{method:"POST",headers:{"content-type":"application/json"},body:payload,keepalive:true})}catch{}}

export default function FunnelTracker(){useEffect(()=>{const start=()=>{persistAttribution();const path=window.location.pathname;const locale=path.startsWith("/en")?"en":path.startsWith("/fr")?"fr":undefined;send({event:"page_view",path,locale});if(path.includes("/garderies"))send({event:"results_view",path,locale})};start();let formStarted=false;const completed=new Set<number>();const onFocus=(event:Event)=>{const target=event.target as HTMLElement|null;if(!target?.closest("form[action='/api/demandes']")||formStarted)return;formStarted=true;send({event:"form_start",path:window.location.pathname,locale:window.location.pathname.startsWith("/en")?"en":"fr"})};const onClick=(event:Event)=>{const target=event.target as HTMLElement|null;const el=target?.closest("a,button") as HTMLAnchorElement|HTMLButtonElement|null;if(!el)return;const step=el.getAttribute("data-funnel-step");if(step){const n=Number(step);if(n&& !completed.has(n)){completed.add(n);send({event:"step_complete",path:window.location.pathname,locale:window.location.pathname.startsWith("/en")?"en":"fr",step:n})}}if(el.closest("form[action='/api/demandes']")&&el.tagName==="BUTTON")return;const href=el instanceof HTMLAnchorElement?el.getAttribute("href")||"":"";const text=(el.textContent||"").trim().toLowerCase();const locale=window.location.pathname.startsWith("/en")?"en":"fr";if(href.includes("/mon-besoin")||text.includes("trouver ma garde")||text.includes("trouver ma solution")||text.includes("find my childcare")||text.includes("find my solution"))send({event:"cta_click",path:window.location.pathname,locale});if(href.includes("/garderie/")&&!href.includes("/garderies?"))send({event:"provider_click",path:window.location.pathname,locale,providerId:href.split("/garderie/")[1]?.split(/[?#]/)[0]})};const onSubmit=(event:Event)=>{const form=event.target as HTMLFormElement|null;if(form?.action.includes("/api/demandes")){send({event:"demand_submitted",path:window.location.pathname,locale:window.location.pathname.startsWith("/en")?"en":"fr"})}};const onConsent=()=>{persistAttribution();send({event:"page_view",path:window.location.pathname,locale:window.location.pathname.startsWith("/en")?"en":"fr"})};document.addEventListener("focusin",onFocus);document.addEventListener("click",onClick);document.addEventListener("submit",onSubmit);window.addEventListener("mycoco-consent",onConsent);return()=>{document.removeEventListener("focusin",onFocus);document.removeEventListener("click",onClick);document.removeEventListener("submit",onSubmit);window.removeEventListener("mycoco-consent",onConsent)}},[]);return null}
