import Link from "next/link";
import { cities as defaultCities } from "@/lib/site";
import { type Locale } from "@/lib/i18n";
import { getChildcareData, typeLabel } from "@/lib/childcare";

export async function BilingualHome({locale,cities=defaultCities}:{locale:Locale;cities?:readonly{slug:string;name:string}[]}) {
 const fr=locale==='fr';
 const data=await getChildcareData();
 const featured=data.records.filter(r=>cities.some(c=>c.name===r.city)).slice(0,3);
 const cta=fr?'Trouver une garde':'Find childcare';
 const steps=fr?[
 ['Votre quotidien, vos critères.','Indiquez votre secteur, l’âge de votre enfant et le type de garde recherché.'],
 ['Vos options, au même endroit.','Consultez les coordonnées et les informations des services pour préparer vos démarches.'],
 ['Un premier contact éclairé.','Contactez le service pour confirmer les places, les horaires et organiser une visite.']
 ]:[['Your routine. Your criteria.','Choose your area, your child’s age and the type of childcare you are looking for.'],['Your options, in one place.','Review provider information and contact details to plan your next steps.'],['A more informed first conversation.','Contact the provider to confirm openings, discuss hours and arrange a visit.']];
 const faqs=fr?[
 ['Est-ce gratuit pour les parents ?','Oui. Vous pouvez rechercher des services et consulter les fiches sans créer de compte.'],
 ['Les services affichés ont-ils une place ?','Une fiche indique qu’un service est répertorié, pas qu’une place est libre. Confirmez toujours la disponibilité directement auprès du service.'],
 ['Puis-je chercher pour un poupon ?','Oui. Choisissez la tranche d’âge correspondant à votre enfant. Les conditions d’accueil et les places pour poupons restent à confirmer auprès du service.'],
 ['MyCoco remplace-t-il les démarches officielles ?','Non. MyCoco vous aide à explorer les services de garde et à préparer vos contacts. Poursuivez les démarches d’inscription officielles du Québec en parallèle.']
 ]:[['Is it free for parents?','Yes. Search providers and browse profiles without creating an account.'],['Do listed providers have openings?','A listing means a provider is in the directory, not that a spot is available. Always confirm availability directly with the provider.'],['Can I search for infant care?','Yes. Choose your child’s age range. Confirm infant admissions and openings directly with each provider.'],['Does MyCoco replace the official process?','No. MyCoco helps you explore childcare services and prepare to contact them. Continue Quebec’s official registration process alongside your search.']];
 return <div className="coco-refresh">
  <section className="coco-hero"><div className="coco-wrap coco-hero-grid"><div>
   <p className="coco-kicker">{fr?'LES FAMILLES DU QUÉBEC ONT UN NOUVEAU REPÈRE':'A NEW START FOR QUEBEC FAMILIES'}</p>
   <h1>{fr?<>Une garde près de chez vous.<br/><em>Une chose de moins à porter.</em></>:<>Childcare close to home.<br/><em>One less thing on your mind.</em></>}</h1>
   <p className="coco-lead">{fr?'CPE, garderie ou milieu familial : explorez les services de votre secteur et sachez qui contacter. Votre recherche commence ici.':'CPE, daycare or home childcare: explore providers in your area and find out who to contact. Your search starts here.'}</p>
   <Link className="coco-button" href={`/${locale}/mon-besoin`}>{cta} <span aria-hidden="true">→</span></Link>
   <p className="coco-reassure">{fr?'Gratuit · Sans compte pour commencer':'Free · No account to start'}</p><Link className="coco-text-link" href={`/${locale}/pour-les-services`}>{fr?"Vous proposez un service de garde ?":"Do you offer childcare?"}</Link>
  </div><div className="coco-search"><span className="coco-kicker">{fr?'ON COMMENCE OÙ ?':'WHERE SHALL WE START?'}</span><h2>{fr?'Près de votre vie.':'Close to your everyday.'}</h2>
   <form action={`/${locale}/garderies`} method="get"><label htmlFor="coco-city">{fr?'Ville ou code postal':'City or postal code'}</label><input id="coco-city" name="ville" placeholder={fr?'Ex. Mirabel ou J7J 1A1':'e.g. Mirabel or J7J 1A1'} required minLength={2} maxLength={120}/><label htmlFor="coco-age">{fr?'Âge de votre enfant':'Your child’s age'}</label><select id="coco-age" name="age" defaultValue=""><option value="">{fr?'Tous les âges':'All ages'}</option><option value="0-18">{fr?'0 à 18 mois':'0–18 months'}</option><option value="18-36">{fr?'18 à 36 mois':'18–36 months'}</option><option value="3-5">{fr?'3 à 5 ans':'3–5 years'}</option><option value="5+">{fr?'5 ans et plus':'5+ years'}</option></select><button className="coco-button" type="submit">{fr?'Explorer les services':'Explore providers'} <span aria-hidden="true">→</span></button></form>
   <p>{fr?'Les disponibilités sont à confirmer auprès de chaque service.':'Confirm openings directly with each provider.'}</p>
  </div></div></section>
  <div className="coco-band"><div className="coco-wrap"><span>{fr?'Votre secteur':'Your neighbourhood'}</span><span>{fr?'Vos critères':'Your criteria'}</span><span>{fr?'Des contacts concrets':'Real contacts'}</span><span>{fr?'À votre rythme':'At your pace'}</span></div></div>
  <section className="coco-section coco-wrap"><p className="coco-kicker">{fr?'DU PREMIER CLIC AU PREMIER CONTACT':'FROM FIRST CLICK TO FIRST CONTACT'}</p><h2>{fr?'Moins de pistes dispersées.\nUne prochaine étape claire.':'Fewer scattered leads.\nA clearer next step.'}</h2><div className="coco-steps">{steps.map(([title,body],i)=><article key={title}><span className="coco-number">0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
  <section className="coco-directory"><div className="coco-wrap coco-section"><div className="coco-heading"><div><p className="coco-kicker">{fr?'MIRABEL ET LES LAURENTIDES':'MIRABEL & THE LAURENTIANS'}</p><h2>{fr?'Tout commence\nprès de chez vous.':'Good beginnings\nstart close to home.'}</h2></div><Link className="coco-text-link" href={`/${locale}/garderies`}>{fr?'Voir l’annuaire':'Browse the directory'} →</Link></div><div className="coco-providers">{featured.map(r=><Link className="coco-provider" href={`/${locale}/garderie/${r.slug}`} key={r.id}><span className="coco-tag">{typeLabel(r.type,fr)}</span><h3>{r.name}</h3><p>{r.city}</p><small>{fr?'Disponibilité à confirmer':'Availability to confirm'}</small><strong>{fr?'Découvrir le service':'View provider'} →</strong></Link>)}</div><div className="coco-cities">{cities.map(c=><Link key={c.slug} href={`/${locale}/garderies/${c.slug}`}>{c.name} <span aria-hidden="true">↗</span></Link>)}</div></div></section>
  <section className="coco-section coco-wrap coco-provider-pitch"><div><p className="coco-kicker">{fr?'VOUS ACCUEILLEZ DES ENFANTS ?':'DO YOU PROVIDE CHILDCARE?'}</p><h2>{fr?'Aidez les familles\nà vous découvrir.':'Help local families\nfind you.'}</h2></div><div><p>{fr?'Présentez votre service aux parents de votre secteur. Une fiche claire les aide à comprendre votre offre avant de vous contacter.':'Introduce your service to parents in your area. A clear profile helps them understand what you offer before reaching out.'}</p><Link className="coco-button" href={`/${locale}/pour-les-services`}>{fr?'Présenter mon service':'List my service'} →</Link><p className="coco-reassure">{fr?'Présence de base gratuite pendant le lancement':'Free basic listing during launch'}</p></div></section>
  <section className="coco-faq coco-wrap coco-section"><div><p className="coco-kicker">{fr?'AVANÇONS EN CONFIANCE':'LET’S MAKE THINGS CLEAR'}</p><h2>{fr?'Vos questions.\nDes réponses claires.':'Your questions.\nClear answers.'}</h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  <section className="coco-final"><div className="coco-wrap"><p className="coco-kicker">{fr?'UNE PREMIÈRE ÉTAPE, AUJOURD’HUI':'YOUR FIRST STEP STARTS HERE'}</p><h2>{fr?'Et si on commençait\npar votre quartier ?':'Let’s start with\nyour neighbourhood.'}</h2><Link className="coco-button" href={`/${locale}/mon-besoin`}>{cta} →</Link><p>{fr?'Quelques critères. Des services à explorer.':'A few details. Local services to explore.'}</p></div></section>
 </div>;
}
