import Link from "next/link";
import { cities } from "@/lib/site";
import { type Locale } from "@/lib/i18n";

type IconName = "pin" | "baby" | "grid" | "search" | "arrow" | "shield" | "heart";
function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const c = { width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true };
  if(name==="pin") return <svg {...c}><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>;
  if(name==="baby") return <svg {...c}><circle cx="12" cy="7" r="3"/><path d="M6.5 21v-4.2a5.5 5.5 0 0 1 11 0V21M9 12.5h6M8 17h8"/></svg>;
  if(name==="grid") return <svg {...c}><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg>;
  if(name==="search") return <svg {...c}><circle cx="10.8" cy="10.8" r="6.5"/><path d="m16 16 4.2 4.2"/></svg>;
  if(name==="arrow") return <svg {...c}><path d="M5 12h13M13 6l6 6-6 6"/></svg>;
  if(name==="shield") return <svg {...c}><path d="M12 3 19 6v5c0 4.5-3 8-7 10-4-2-7-5.5-7-10V6l7-3Z"/><path d="m9 12 2 2 4-4"/></svg>;
  return <svg {...c}><path d="M20.8 8.9c0 5.2-8.8 10.3-8.8 10.3S3.2 14.1 3.2 8.9A4.7 4.7 0 0 1 12 6a4.7 4.7 0 0 1 8.8 2.9Z"/></svg>;
}

export function BilingualHome({ locale }: { locale: Locale }) {
  const fr = locale === "fr";
  const benefits = fr ? [
    {icon:"pin" as IconName,title:"Trouvez près de chez vous",text:"Recherchez par ville ou code postal et concentrez-vous sur les options qui comptent vraiment pour votre famille."},
    {icon:"search" as IconName,title:"Trouvez la solution adaptée",text:"MyCoco vous aide à affiner votre recherche selon votre réalité, au lieu de vous laisser parcourir un simple annuaire."},
    {icon:"heart" as IconName,title:"Ne restez plus sans solution",text:"Demain, MyCoco pourra vous aider à retrouver une solution lorsque votre besoin change, qu'une place se libère ou qu'une garde de remplacement devient nécessaire."},
  ] : [
    {icon:"pin" as IconName,title:"Find care near you",text:"Search by city or postal code and focus on the options that truly fit your family."},
    {icon:"search" as IconName,title:"Find the right solution",text:"MyCoco helps narrow your search around your real needs instead of leaving you with a simple directory."},
    {icon:"heart" as IconName,title:"Never be left without a solution",text:"Over time, MyCoco can help when your needs change, a spot opens or backup care is needed."},
  ];
  return <main>
    <section className="home-hero"><div className="home-container hero-layout"><div className="hero-copy">
      <div className="location-badge"><span className="badge-dot"/> Québec · Canada</div><span className="hero-kicker">MYCOCO · {fr?"GARDE D’ENFANTS":"CHILDCARE"}</span>
      <h1>{fr?<>La garde qui s’adapte à <em>votre famille.</em></>:<>Childcare that fits <em>your family.</em></>}</h1>
      <p>{fr?"Trouvez une garderie, un CPE ou un service de garde près de chez vous. MyCoco vous aide à trouver la bonne solution aujourd’hui — et à vous adapter lorsque vos besoins changent.":"Find a daycare, CPE or childcare service near you. MyCoco helps you find the right solution today — and adapt when your needs change."}</p>
      <div className="hero-actions"><Link className="hero-primary" href={`/${locale}/mon-besoin`}>{fr?"Trouver ma solution":"Find my solution"}<Icon name="arrow" size={18}/></Link><Link className="hero-note" href={`/${locale}/garderies`}><Icon name="search" size={16}/> {fr?"Explorer les garderies":"Browse childcare"}</Link></div>
    </div><div className="hero-search-wrap"><div className="search-card-new">
      <div className="search-card-head"><div className="search-icon-box"><Icon name="search" size={21}/></div><div><strong>{fr?"Trouvez votre solution de garde":"Find your childcare solution"}</strong><span>{fr?"Commencez avec trois informations simples.":"Start with three simple details."}</span></div></div>
      <form action={`/${locale}/garderies`} method="get"><label className="search-field full-field"><span>{fr?"Où avez-vous besoin de garde ?":"Where do you need childcare?"}</span><div className="field-control"><Icon name="pin" size={18}/><input name="ville" placeholder={fr?"Ville ou code postal":"City or postal code"} autoComplete="postal-code"/></div></label>
      <div className="search-row"><label className="search-field"><span>{fr?"Âge de l’enfant":"Child's age"}</span><div className="field-control"><Icon name="baby" size={18}/><select name="age" defaultValue=""><option value="">{fr?"Sélectionner":"Select"}</option><option value="0-18">0–18 mois</option><option value="18-36">18–36 mois</option><option value="3-5">3–5 ans</option></select></div></label><label className="search-field"><span>{fr?"Type de garde":"Childcare type"}</span><div className="field-control"><Icon name="grid" size={18}/><select name="type" defaultValue=""><option value="">{fr?"Tous les types":"All types"}</option><option value="cpe">CPE</option><option value="subventionnee">{fr?"Garderie subventionnée":"Subsidized daycare"}</option><option value="milieu-familial">{fr?"Milieu familial":"Home daycare"}</option><option value="non-subventionnee">{fr?"Garderie non subventionnée":"Non-subsidized daycare"}</option></select></div></label></div>
      <button className="search-submit" type="submit">{fr?"Voir les solutions":"See childcare options"}<Icon name="arrow" size={18}/></button></form><div className="search-footer"><span>✓ {fr?"Sans inscription":"No account required"}</span><span>✓ {fr?"Partout au Québec":"Across Quebec"}</span></div>
    </div><div className="floating-card"><div className="mini-icon"><Icon name="heart" size={17}/></div><div><strong>{fr?"Pensé pour les familles":"Built for families"}</strong><span>{fr?"Simple · local · bilingue":"Simple · local · bilingual"}</span></div></div></div></div></section>
    <section className="trust-strip"><div className="home-container trust-inner"><span>{fr?"Une recherche locale, pensée pour les familles du Québec":"Local search, built for Quebec families"}</span><div><span><Icon name="pin" size={16}/> Québec</span><span><Icon name="shield" size={16}/> {fr?"Gratuite":"Free"}</span><span><Icon name="heart" size={16}/> {fr?"Français & English":"French & English"}</span></div></div></section>
    <section className="benefits-section"><div className="home-container"><div className="section-heading"><span className="section-kicker">{fr?"POURQUOI MYCOCO":"WHY MYCOCO"}</span><h2>{fr?"Pas seulement trouver une place. Trouver la bonne solution.":"Not just a spot. The right childcare solution."}</h2><p>{fr?"MyCoco commence par la recherche, mais construit progressivement une plateforme capable de connecter les besoins des familles aux solutions de garde disponibles.":"MyCoco starts with search, but is progressively building a platform that can connect family needs with available childcare solutions."}</p></div><div className="benefit-grid">{benefits.map((item,i)=><article className="benefit-card" key={item.title}><div className="benefit-number">0{i+1}</div><div className="benefit-icon"><Icon name={item.icon} size={22}/></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
    <section className="city-section-new"><div className="home-container"><div className="section-heading compact"><span className="section-kicker">{fr?"PRÈS DE CHEZ VOUS":"NEAR YOU"}</span><h2>{fr?"Commencez local. Pensez famille.":"Start local. Think family."}</h2><p>{fr?"Explorez les secteurs où MyCoco commence à bâtir un réseau de garde utile, local et bilingue.":"Explore the areas where MyCoco is starting to build a useful, local and bilingual childcare network."}</p></div><div className="city-grid-new">{cities.map(city=><Link className="city-card-new" key={city.slug} href={`/${locale}/garderie/${city.slug}`}><div><span className="city-pin"><Icon name="pin" size={17}/></span><strong>{city.name}</strong><small>{fr?"Garderies et services de garde":"Daycares and childcare"}</small></div><span className="city-arrow"><Icon name="arrow" size={17}/></span></Link>)}</div></div></section>
    <section className="future-section"><div className="home-container future-layout"><div><span className="section-kicker light">{fr?"L’UNIVERS MYCOCO":"THE MYCOCO ECOSYSTEM"}</span><h2>{fr?"Une place aujourd’hui. Une solution quand la vie change.":"A place today. A solution when life changes."}</h2><p className="future-intro">{fr?"MyCoco commence par la recherche de garde, mais notre ambition va plus loin : aider les familles à gérer leurs besoins de garde au fil du temps.":"MyCoco starts with childcare search, but our ambition goes further: helping families manage their childcare needs as life changes."}</p></div><div className="future-list"><div><span>01</span><p>{fr?"Garde régulière":"Regular childcare"}</p></div><div><span>02</span><p>{fr?"Garde de remplacement":"Backup care"}</p></div><div><span>03</span><p>{fr?"Besoins ponctuels":"Occasional care"}</p></div></div></div></section>
    <section className="bottom-cta"><div className="home-container bottom-cta-inner"><div><span className="section-kicker">{fr?"COMMENCEZ MAINTENANT":"START NOW"}</span><h2>{fr?"Trouvez votre solution de garde.":"Find your childcare solution."}</h2></div><Link className="hero-primary" href={`/${locale}/mon-besoin`}>{fr?"Trouver ma solution":"Find my solution"}<Icon name="arrow" size={18}/></Link></div></section>
  </main>;
}
