"use client";

import { FormEvent, useMemo, useState } from "react";

type Props={locale:"fr"|"en";error?:string;initialCity?:string};

export default function NeedWizard({locale,error="",initialCity=""}:Props){
  const fr=locale==="fr";const[step,setStep]=useState(1);const[ville,setVille]=useState(initialCity);const[age,setAge]=useState("");const[type,setType]=useState("");const[debut,setDebut]=useState("");
  const canContinue=useMemo(()=>step===1?ville.trim().length>=2:step===2?Boolean(age):true,[step,ville,age]);
  const next=()=>setStep(current=>Math.min(4,current+1));const back=()=>setStep(current=>Math.max(1,current-1));
  const submit=(event:FormEvent<HTMLFormElement>)=>{if(step<4){event.preventDefault();next()}};
  const ageLabel=age==="0-18"?(fr?"0–18 mois":"0–18 months"):age==="18-36"?(fr?"18–36 mois":"18–36 months"):age==="3-5"?(fr?"3–5 ans":"3–5 years"):age==="5+"?(fr?"5 ans et +":"5+ years"):"";
  const typeLabel=type===""?(fr?"Toutes les solutions":"All options"):type==="cpe"?"CPE":type==="subventionnee"?(fr?"Garderie subventionnée":"Subsidized daycare"):type==="milieu-familial"?(fr?"Milieu familial":"Home childcare"):(fr?"Garderie non subventionnée":"Non-subsidized daycare");
  return <form className="mc-wizard14" action="/api/demandes" method="post" onSubmit={submit}>
    <input type="hidden" name="locale" value={locale}/><input type="hidden" name="ville" value={ville}/><input type="hidden" name="age" value={age}/><input type="hidden" name="type" value={type}/><input type="hidden" name="debut" value={debut}/><input className="mc-hp" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/>
    {error&&<div className="mc-wizard14-error" role="alert">{error}</div>}
    <div className="mc-wizard14-top"><div><span>{fr?"VOTRE RECHERCHE":"YOUR SEARCH"}</span><strong>{fr?`Étape ${step} sur 4`:`Step ${step} of 4`}</strong></div><span>{fr?"Sans compte · gratuit":"No account · free"}</span></div>
    <div className="mc-wizard14-progress" aria-label={fr?`Étape ${step} sur 4`:`Step ${step} of 4`}>{[1,2,3,4].map(n=><span key={n} className={n<=step?"on":""}/>)}</div>
    {step===1&&<section className="mc-wizard14-step"><span>01</span><h2>{fr?"Où votre enfant doit-il être gardé ?":"Where do you need childcare?"}</h2><p>{fr?"Commencez par la zone qui compte vraiment au quotidien : maison, travail ou trajet. Vous pourrez élargir ensuite.":"Start with the area that really matters day to day: home, work or commute. You can broaden it later."}</p><label><span>{fr?"Ville ou code postal":"City or postal code"}</span><input data-funnel-step="1" autoFocus value={ville} onChange={e=>setVille(e.target.value)} placeholder={fr?"Ex. Mirabel ou J7J 1A1":"e.g. Mirabel or J7J 1A1"} autoComplete="postal-code"/></label></section>}
    {step===2&&<section className="mc-wizard14-step"><span>02</span><h2>{fr?"Quel âge a votre enfant ?":"How old is your child?"}</h2><p>{fr?"L’âge permet d’écarter les services qui ne correspondent pas au groupe recherché. Aucun nom ni date de naissance complète n’est nécessaire pour cette recherche.":"Age helps remove services that do not fit the relevant group. No full name or exact birth date is needed for this search."}</p><div className="mc-choice-grid14">{[["0-18",fr?"0 à 18 mois":"0–18 months"],["18-36",fr?"18 à 36 mois":"18–36 months"],["3-5",fr?"3 à 5 ans":"3–5 years"],["5+",fr?"5 ans et +":"5+ years"]].map(([value,label])=><button data-funnel-step="2" type="button" key={value} className={age===value?"selected":""} onClick={()=>setAge(value)}>{label}{age===value?"  ✓":""}</button>)}</div></section>}
    {step===3&&<section className="mc-wizard14-step"><span>03</span><h2>{fr?"Avez-vous une préférence de garde ?":"Do you have a care preference?"}</h2><p>{fr?"Vous n’avez pas besoin de maîtriser les catégories. Si vous hésitez, gardez toutes les options ouvertes.":"You do not need to know every category. If you are unsure, keep all options open."}</p><div className="mc-choice-list14">{[["",fr?"Je suis ouvert à toutes les solutions":"I’m open to all options"],["cpe","CPE"],["subventionnee",fr?"Garderie subventionnée":"Subsidized daycare"],["milieu-familial",fr?"Milieu familial":"Home childcare"],["non-subventionnee",fr?"Garderie non subventionnée":"Non-subsidized daycare"]].map(([value,label])=><button data-funnel-step="3" type="button" key={label} className={type===value?"selected":""} onClick={()=>setType(value)}><span>{label}</span><b>{type===value?"✓":""}</b></button>)}</div></section>}
    {step===4&&<section className="mc-wizard14-step"><span>04</span><h2>{fr?"Quand en avez-vous besoin ?":"When do you need care?"}</h2><p>{fr?"La date est facultative. Elle nous aide surtout à structurer votre besoin pour la suite.":"The date is optional. It mainly helps structure your need for what comes next."}</p><label><span>{fr?"Date souhaitée (facultatif)":"Desired date (optional)"}</span><input data-funnel-step="4" type="date" value={debut} onChange={e=>setDebut(e.target.value)}/></label><div style={{marginTop:18,padding:14,borderRadius:13,background:"#f7f7f5",fontSize:11,color:"#697180"}}><strong style={{display:"block",color:"#17233b",marginBottom:6}}>{fr?"Votre recherche":"Your search"}</strong>{ville} · {ageLabel}<br/>{typeLabel}{debut?` · ${debut}`:""}</div></section>}
    <div className="mc-wizard14-actions">{step>1?<button type="button" className="mc-wizard14-back" onClick={back}>← {fr?"Retour":"Back"}</button>:<span/>}<button type="submit" className="mc-wizard14-next" disabled={!canContinue}>{step===4?(fr?"Voir mes options":"See my options"):(fr?"Continuer":"Continue")} →</button></div>
    <p style={{textAlign:"center",margin:"11px 0 0",color:"#89909a",fontSize:9}}>{fr?"MyCoco affiche des options pertinentes. Une place et une admission doivent toujours être confirmées selon le processus applicable.":"MyCoco shows relevant options. A spot and admission must always be confirmed through the applicable process."}</p>
  </form>;
}
