import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getChildcareData, typeLabel } from "@/lib/childcare";
import { isLocale, locales } from "@/lib/i18n";

export async function generateStaticParams(){const data=await getChildcareData();return locales.flatMap(locale=>data.records.slice(0,500).map(record=>({locale,slug:record.slug})))}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}):Promise<Metadata>{const{locale:raw,slug}=await params;if(!isLocale(raw))return{};const data=await getChildcareData();const record=data.records.find(r=>r.slug===slug);if(!record)return{};const fr=raw==="fr";return{title:`${record.name} | ${typeLabel(record.type,fr)} à ${record.city}`,description:fr?`${record.name}, ${typeLabel(record.type,true)} à ${record.city}. Consultez les informations publiques disponibles et confirmez la disponibilité directement avec le service.`:`${record.name}, ${typeLabel(record.type,false)} in ${record.city}. Review available public information and confirm availability directly.`,alternates:{canonical:`/${raw}/garderie/${record.slug}`},robots:{index:true,follow:true}}}

export default async function ProviderPage({params,searchParams}:{params:Promise<{locale:string;slug:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const{locale:raw,slug}=await params;if(!isLocale(raw))notFound();const q=await searchParams;const demandId=typeof q.demandeId==="string"?q.demandeId:"";const interestSent=q.interet==="envoye";const data=await getChildcareData();const record=data.records.find(r=>r.slug===slug);if(!record)notFound();const fr=raw==="fr";const kind=typeLabel(record.type,fr);const address=[record.address,record.city,record.postalCode].filter(Boolean).join(" · ");
  return <main className="mc-directory-page">
    <section className="mc-profile14-head"><div className="mc-shell"><div className="mc-breadcrumb"><Link href={`/${raw}`}>MyCoco</Link><span>›</span><Link href={`/${raw}/garderies`}>{fr?"Annuaire":"Directory"}</Link><span>›</span><span>{record.city}</span></div><div className="mc-profile14-hero"><div className="mc-profile14-id"><div className="mc-profile14-avatar"><b>{record.name.slice(0,1).toUpperCase()}</b><span>{fr?"FICHE RÉPERTORIÉE":"LISTED PROFILE"}</span></div><div className="mc-profile14-title"><span className="mc-kicker">{kind}</span><h1>{record.name}</h1><p>{address||record.city}</p><div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:14}}><span style={{padding:"7px 9px",borderRadius:999,background:"#fff",border:"1px solid #e2e5e9",fontSize:8,fontWeight:850}}>✓ {fr?"Données publiques structurées":"Structured public data"}</span><span style={{padding:"7px 9px",borderRadius:999,background:"#fff",border:"1px solid #e2e5e9",fontSize:8,fontWeight:850}}>✓ {fr?"Disponibilité non inventée":"No invented availability"}</span></div></div></div><div className="mc-profile14-claim"><small>{fr?"VOUS GÉREZ CE SERVICE ?":"DO YOU MANAGE THIS PROVIDER?"}</small><strong>{fr?"Prenez le contrôle de cette fiche.":"Take control of this profile."}</strong><p>{fr?"Ajoutez les informations que vous contrôlez directement : horaires, coordonnées, photos autorisées et, lorsque la fonction est active, vos disponibilités.":"Add the information you directly control: hours, contact details, authorized photos and, when enabled, openings."}</p><Link href={`/${raw}/inscription?role=provider`}>{fr?"Créer mon espace service":"Create provider space"}<b>→</b></Link></div></div></div></section>
    <section className="mc-profile14-body"><div className="mc-shell mc-profile14-grid"><article><div className="mc-profile14-section"><span className="mc-kicker">{fr?"CE QUE L’ON SAIT":"WHAT WE KNOW"}</span><h2>{fr?"Une fiche utile sans faire semblant d’en savoir plus.":"A useful profile without pretending to know more."}</h2><p>{fr?"MyCoco rassemble les informations disponibles pour faciliter la comparaison. Une capacité déclarée n’est jamais transformée en disponibilité réelle et aucune image générique n’est présentée comme une photo de cet établissement.":"MyCoco brings available information together for easier comparison. Listed capacity is never turned into live availability, and generic imagery is never presented as a real provider photo."}</p><div className="mc-profile14-facts"><div><small>TYPE</small><strong>{kind}</strong></div><div><small>{fr?"SECTEUR":"AREA"}</small><strong>{record.city}</strong></div><div><small>{fr?"CAPACITÉ":"CAPACITY"}</small><strong>{record.capacityTotal?String(record.capacityTotal):(fr?"À confirmer":"To confirm")}</strong></div><div><small>{fr?"DISPONIBILITÉ":"AVAILABILITY"}</small><strong>{fr?"À confirmer":"To confirm"}</strong></div></div></div>
      {(record.phone||record.address)&&<div className="mc-profile14-section"><span className="mc-kicker">{fr?"COORDONNÉES PUBLIQUES":"PUBLIC CONTACT"}</span><h2>{fr?"Contacter le service":"Contact provider"}</h2>{record.phone&&<a className="mc-contact-row" href={`tel:${record.phone.replace(/[^\d+]/g,"")}`}><span>{fr?"Téléphone":"Phone"}</span><strong>{record.phone}</strong><b>↗</b></a>}{record.address&&<div className="mc-contact-row"><span>{fr?"Adresse":"Address"}</span><strong>{record.address}{record.postalCode?` · ${record.postalCode}`:""}</strong><b/></div>}</div>}
      <div className="mc-data-note"><span>i</span><p><strong>{fr?"Transparence des données":"Data transparency"}</strong><br/>{fr?"Une présence dans MyCoco ne garantit jamais une place. La disponibilité et l’admission doivent être confirmées selon le processus applicable.":"Being listed on MyCoco never guarantees a spot. Availability and admission must be confirmed through the applicable process."}{data.updatedAt?` · ${fr?"Données":"Data"} ${new Date(data.updatedAt).toLocaleDateString(fr?"fr-CA":"en-CA")}`:""}</p></div></article>
      <aside className="mc-profile14-action">{interestSent?<><span className="mc-kicker">{fr?"INTÉRÊT ENREGISTRÉ":"INTEREST SAVED"}</span><h2>{fr?"Cette option est maintenant liée à votre recherche.":"This option is now linked to your search."}</h2><p>{fr?"Continuez à comparer. Une bonne décision se prend rarement avec une seule fiche.":"Keep comparing. A good decision rarely comes from a single profile."}</p><Link href={`/${raw}/garderies`}>{fr?"Voir d’autres services":"See other providers"} →</Link></>:demandId?<><span className="mc-kicker">MYCOCO MATCH</span><h2>{fr?"Vous voulez garder ce service dans votre parcours ?":"Want to keep this provider in your journey?"}</h2><p>{fr?"Enregistrez votre intérêt. Cela relie la fiche à votre besoin sans prétendre qu’une place est disponible.":"Save your interest. This links the profile to your need without implying a spot is available."}</p><form method="post" action="/api/leads"><input type="hidden" name="locale" value={raw}/><input type="hidden" name="providerSlug" value={record.slug}/><input type="hidden" name="demandId" value={demandId}/><input type="hidden" name="source" value="provider-profile"/><button type="submit">{fr?"Ajouter à ma recherche":"Add to my search"} →</button></form></>:<><span className="mc-kicker">MYCOCO MATCH</span><h2>{fr?"Cette fiche est une option. Votre besoin permet de savoir si elle est pertinente.":"This profile is one option. Your needs tell us whether it is relevant."}</h2><p>{fr?"Indiquez votre secteur, l’âge de votre enfant et vos critères essentiels pour voir les services à examiner en priorité.":"Tell us your area, child age and key criteria to see which providers deserve attention first."}</p><Link href={`/${raw}/mon-besoin`}>{fr?"Trouver ma garde":"Find childcare"} →</Link></>}</aside></div></section>
  </main>;
}
