import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n";

export default async function ProviderSpacePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const fr = locale === "fr";
  return <main className="mc-provider-space-v2">
    <section className="mc-ps2-hero"><div className="mc-ps2-wrap"><span className="mc-ps2-eyebrow">MYCOCO · {fr ? "ESPACE SERVICE" : "PROVIDER SPACE"}</span><div className="mc-ps2-grid"><div><h1>{fr ? "Votre établissement mérite mieux qu'une ligne dans un annuaire." : "Your childcare service deserves more than a line in a directory."}</h1><p>{fr ? "Créez votre espace MyCoco, contrôlez votre fiche et présentez clairement votre service aux familles qui recherchent dans votre secteur." : "Create your MyCoco space, control your profile and present your service clearly to families searching in your area."}</p><div className="mc-ps2-actions"><Link className="mc-ps2-primary" href={`/${locale}/pour-les-services`}>{fr ? "Comprendre MyCoco" : "Understand MyCoco"} →</Link><Link className="mc-ps2-secondary" href={`/${locale}/garderies`}>{fr ? "Voir les fiches" : "See profiles"}</Link></div></div><div className="mc-ps2-card"><span>{fr ? "VOTRE ESPACE SERVICE" : "YOUR PROVIDER SPACE"}</span><h2>{fr ? "Un profil que vous pouvez vraiment maîtriser." : "A profile you can actually control."}</h2>{[["01",fr?"Identité et coordonnées":"Identity and contact"],["02",fr?"Horaires et capacité":"Hours and capacity"],["03",fr?"Âges et services":"Ages and services"],["04",fr?"Photos et présentation":"Photos and presentation"],["05",fr?"Demandes et statistiques":"Leads and analytics"]].map(([n,t])=><div key={n}><b>{n}</b><span>{t}</span></div>)}</div></div></div></section>
    <section className="mc-ps2-body"><div className="mc-ps2-wrap"><div className="mc-ps2-heading"><span>{fr ? "LE PARCOURS SERVICE" : "PROVIDER JOURNEY"}</span><h2>{fr ? "Créer d'abord de la valeur. Monétiser ensuite." : "Create value first. Monetize later."}</h2><p>{fr ? "Le lancement doit rester simple : une présence de base gratuite, une fiche complète et une meilleure compréhension de la demande locale. Les outils payants arrivent lorsque MyCoco génère réellement de la valeur." : "Launch stays simple: free basic presence, a complete profile and better visibility into local demand. Paid tools come once MyCoco genuinely creates value."}</p></div><div className="mc-ps2-flow">{[["01",fr?"Créer":"Create",fr?"Votre espace service et votre identité.":"Your provider space and identity."],["02",fr?"Compléter":"Complete",fr?"Capacité, horaires, âges, tarifs et photos.":"Capacity, hours, ages, pricing and photos."],["03",fr?"Être trouvé":"Get discovered",fr?"Une fiche locale claire et indexable.":"A clear, local, searchable profile."],["04",fr?"Recevoir":"Receive",fr?"À terme, demandes et leads réellement pertinents.":"Over time, genuinely relevant demand and leads."]].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></article>)}</div><div className="mc-ps2-business"><span>{fr?"MONÉTISATION À TERME":"LONG-TERM MONETIZATION"}</span><strong>{fr?"MyCoco Pro · leads qualifiés · visibilité · gestion des demandes · transactions":"MyCoco Pro · qualified leads · visibility · demand management · transactions"}</strong></div></div></section>
    <style>{`.mc-provider-space-v2{background:#f7f2e9;color:#18352c}.mc-ps2-wrap{width:min(1160px,calc(100% - 40px));margin:auto}.mc-ps2-hero{padding:72px 0 84px;background:#18352c;color:#fff}.mc-ps2-eyebrow,.mc-ps2-heading>span{font-size:10px;font-weight:950;letter-spacing:.14em;color:#a9c9b8}.mc-ps2-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:80px;align-items:center;margin-top:17px}.mc-ps2-grid h1{font-size:clamp(45px,6vw,75px);line-height:.96;letter-spacing:-.068em;margin:0 0 22px}.mc-ps2-grid>div>p{max-width:690px;color:#d1ded8;font-size:18px;line-height:1.6}.mc-ps2-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:27px}.mc-ps2-primary,.mc-ps2-secondary{display:inline-flex;padding:14px 18px;border-radius:12px;font-size:12px;font-weight:900}.mc-ps2-primary{background:#fff;color:#18352c}.mc-ps2-secondary{border:1px solid rgba(255,255,255,.22);color:#fff}.mc-ps2-card{padding:26px;background:#f9f6ef;color:#18352c;border-radius:24px;box-shadow:0 24px 65px rgba(0,0,0,.15)}.mc-ps2-card>span{font-size:9px;font-weight:950;letter-spacing:.14em;color:#688175}.mc-ps2-card h2{font-size:23px;line-height:1.06;letter-spacing:-.04em;margin:17px 0}.mc-ps2-card>div{display:flex;align-items:center;gap:12px;padding:11px 0;border-top:1px solid #e1e5de}.mc-ps2-card b{font-size:9px;color:#c47745}.mc-ps2-card span:not(:first-child){font-size:11px;font-weight:800}.mc-ps2-body{padding:82px 0}.mc-ps2-heading{max-width:790px}.mc-ps2-heading h2{font-size:clamp(34px,4.5vw,55px);line-height:1;letter-spacing:-.055em;margin:12px 0}.mc-ps2-heading p{color:#697971;font-size:16px;line-height:1.65}.mc-ps2-flow{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:38px}.mc-ps2-flow article{padding:25px;background:#fff;border:1px solid #dfe4dd;border-radius:19px}.mc-ps2-flow b{font-size:10px;color:#c47745}.mc-ps2-flow h3{font-size:21px;letter-spacing:-.035em;margin:31px 0 10px}.mc-ps2-flow p{font-size:12px;line-height:1.6;color:#718079;margin:0}.mc-ps2-business{margin-top:25px;padding:23px 25px;border-radius:18px;background:#e7eee8}.mc-ps2-business span{display:block;font-size:9px;font-weight:950;letter-spacing:.13em;color:#507662}.mc-ps2-business strong{display:block;font-size:14px;line-height:1.5;margin-top:8px}@media(max-width:900px){.mc-ps2-grid{grid-template-columns:1fr;gap:35px}.mc-ps2-flow{grid-template-columns:1fr 1fr}}@media(max-width:560px){.mc-ps2-hero{padding:52px 0 62px}.mc-ps2-flow{grid-template-columns:1fr}}
    `}</style>
  </main>;
}
