import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n";

export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const{locale}=await params;if(!isLocale(locale))return{};const fr=locale==="fr";return{title:fr?"À propos de MyCoco | Pourquoi nous construisons une nouvelle façon de trouver une garde":"About MyCoco | Why we are building a better childcare search",description:fr?"MyCoco part d’un problème simple : trouver une garde prend trop de temps et manque de clarté. Notre mission est de connecter les familles aux bonnes solutions, puis de bâtir l’écosystème utile autour de l’enfant.":"MyCoco starts from a simple problem: childcare search takes too much time and lacks clarity. Our mission is to connect families with the right options, then build the useful ecosystem around children."};}

export default async function AboutPage({params}:{params:Promise<{locale:string}>}){const{locale}=await params;if(!isLocale(locale))notFound();const fr=locale==="fr";const principles=fr?[["01","Partir du problème, pas du catalogue","Une famille ne cherche pas “une fiche”. Elle cherche une solution compatible avec sa réalité."],["02","Construire la confiance avant la monétisation","Aucune fausse disponibilité, aucun faux avis, aucune photo générique présentée comme réelle."],["03","Densifier localement avant de s’étendre","Une marketplace vide partout vaut moins qu’une marketplace utile dans quelques villes."],["04","Faire de la garde le point d’entrée","Une fois la confiance gagnée, le même espace peut connecter activités, camps, professionnels et solutions de secours."]]:[["01","Start from the problem, not the catalog","A family is not looking for a listing. It is looking for an option that fits real life."],["02","Build trust before monetization","No fake availability, fake reviews or generic photos presented as real."],["03","Build local density before expanding","An empty marketplace everywhere is less useful than a dense one in a few cities."],["04","Use childcare as the entry point","Once trust exists, the same space can connect activities, camps, professionals and backup care."]];return <main>
<section className="mc-content-hero"><div className="mc-shell"><span className="mc-kicker">MYCOCO · {fr?"POURQUOI ON EXISTE":"WHY WE EXIST"}</span><h1 className="mc-display">{fr?"Trouver une garde ne devrait pas devenir un deuxième emploi.":"Finding childcare should not become a second job."}</h1><p className="mc-lead">{fr?"Les familles jonglent entre listes, groupes, appels, sites et informations qui vieillissent vite. Les services de garde, eux, doivent se rendre visibles sans perdre leur temps. MyCoco veut réduire cette friction des deux côtés.":"Families juggle lists, groups, calls, websites and information that ages quickly. Providers need visibility without wasting time. MyCoco is built to reduce friction on both sides."}</p><Link className="mc-btn mc-btn-primary" href={`/${locale}/mon-besoin`} style={{marginTop:24}}>{fr?"Trouver une garde":"Find childcare"} →</Link></div></section>
<section className="mc-content-body"><div className="mc-shell"><span className="mc-kicker">{fr?"NOTRE THÈSE":"OUR THESIS"}</span><h2 className="mc-h2">{fr?"Pas seulement trouver une place. Trouver la bonne solution.":"Not just finding a spot. Finding the right solution."}</h2><div className="mc-split"><div className="mc-panel soft-aqua"><h2>{fr?"Pour les familles":"For families"}</h2><p>{fr?"Commencer par le besoin, voir de la valeur avant de créer un compte, comparer avec transparence, puis conserver sa recherche, ses favoris et ses alertes dans un espace privé.":"Start from the need, see value before creating an account, compare transparently, then keep searches, favourites and alerts in a private space."}</p></div><div className="mc-panel soft-coral"><h2>{fr?"Pour les services":"For providers"}</h2><p>{fr?"Contrôler sa présence, expliquer son offre, maintenir des informations utiles et, progressivement, recevoir une demande locale plus qualifiée qu’un simple trafic de visiteurs.":"Control presence, explain the offer, maintain useful information and progressively receive better-qualified local demand than anonymous traffic."}</p></div></div></div></section>
<section className="mc-content-body" style={{background:"#f7f7f5"}}><div className="mc-shell"><span className="mc-kicker">{fr?"NOS PRINCIPES PRODUIT":"OUR PRODUCT PRINCIPLES"}</span><div className="mc-split" style={{marginTop:24}}>{principles.map(([n,t,d])=><article className="mc-panel" key={n}><b style={{color:"#d9584d",fontSize:10}}>{n}</b><h2>{t}</h2><p>{d}</p></article>)}</div></div></section>
<section className="mc-dark-section"><div className="mc-shell"><span className="mc-kicker">{fr?"UNE AMBITION PLUS LARGE":"A BROADER AMBITION"}</span><h2 className="mc-h2">{fr?"La garde est le point de départ. L’écosystème enfant est la destination.":"Childcare is the starting point. The child ecosystem is the destination."}</h2><p className="mc-lead">{fr?"MyCoco veut progressivement réunir garde, activités, camps, événements, professionnels spécialisés, solutions de secours et avantages employeurs autour d’un même profil famille — avec les mêmes exigences de confiance et de contrôle des données.":"MyCoco aims to progressively connect childcare, activities, camps, events, specialized professionals, backup care and employer benefits around one family profile — with the same standards for trust and data control."}</p><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:23}}><Link className="mc-btn mc-btn-primary" href={`/${locale}/mon-besoin`}>{fr?"Commencer par la garde":"Start with childcare"} →</Link><Link className="mc-btn mc-btn-outline" href={`/${locale}/comment-ca-marche`}>{fr?"Voir le fonctionnement":"See how it works"}</Link></div></div></section>
</main>}
