import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  const fr = locale === "fr";
  return { title: fr ? "À propos de MyCoco" : "About MyCoco", description: fr ? "Pourquoi MyCoco existe et comment nous voulons simplifier la recherche de garde au Québec." : "Why MyCoco exists and how we want to simplify childcare discovery in Quebec." };
}

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const fr = locale === "fr";
  return <main className="mc-about-v2">
    <section className="mc-about-hero"><div><span>MYCOCO · {fr ? "À PROPOS" : "ABOUT"}</span><h1>{fr ? "Pas seulement trouver une place. Trouver la bonne solution." : "Not just finding a spot. Finding the right solution."}</h1><p>{fr ? "MyCoco part d'un problème très concret : les familles doivent souvent naviguer entre listes, appels, groupes et informations incomplètes pour comprendre leurs options. Nous voulons transformer cette recherche en parcours clair." : "MyCoco starts from a concrete problem: families often navigate lists, calls, groups and incomplete information just to understand their options. We want to turn that search into a clear journey."}</p></div></section>
    <section className="mc-about-section"><div className="mc-about-wrap"><div className="mc-about-grid"><div><span>01</span><h2>{fr ? "Une famille avant un annuaire" : "A family before a directory"}</h2></div><p>{fr ? "Un annuaire répond à « qu'est-ce qui existe ? ». MyCoco veut aussi répondre à « qu'est-ce qui pourrait me convenir ? ». C'est pourquoi le besoin famille devient le point de départ du produit." : "A directory answers 'what exists?'. MyCoco also wants to answer 'what could fit me?'. That's why the family's need is the starting point."}</p></div></div></section>
    <section className="mc-about-section soft"><div className="mc-about-wrap"><div className="mc-about-cards"><article><b>Familles</b><h3>{fr ? "Découvrir, comparer, suivre." : "Discover, compare, keep searching."}</h3><p>{fr ? "Un profil et des besoins réutilisables pour éviter de recommencer à zéro." : "A reusable profile and needs so families don't restart from zero."}</p></article><article><b>Services</b><h3>{fr ? "Être visible et maîtriser sa fiche." : "Get discovered and control your page."}</h3><p>{fr ? "Un espace service complet pour présenter l'offre, les capacités et les informations utiles." : "A complete provider space to present the service, capacity and useful information."}</p></article><article><b>Confiance</b><h3>{fr ? "Dire clairement ce qui est vérifié." : "Be clear about what is verified."}</h3><p>{fr ? "Les données publiques, les informations déclarées et la disponibilité réelle doivent rester distinctes." : "Public data, provider-declared information and real availability must remain distinct."}</p></article></div></div></section>
    <section className="mc-about-section"><div className="mc-about-wrap mc-about-end"><span>{fr ? "NOTRE AMBITION" : "OUR AMBITION"}</span><h2>{fr ? "Commencer par la garde. Devenir le réflexe famille." : "Start with childcare. Become the family reflex."}</h2><p>{fr ? "Garde, activités, camps, événements, professionnels de l'enfance et solutions de secours : nous voulons progressivement construire le réseau utile autour de l'enfant." : "Childcare, activities, camps, events, child professionals and backup solutions: we want to progressively build the useful network around children."}</p><Link href={`/${locale}/mon-besoin`}>{fr ? "Commencer ma recherche" : "Start my search"} →</Link></div></section>
    <style>{`.mc-about-v2{background:#fbfaf6;color:#162b24}.mc-about-hero{padding:90px 0;background:#162b24;color:#fff}.mc-about-hero>div,.mc-about-wrap{width:min(1080px,calc(100% - 40px));margin:auto}.mc-about-hero span,.mc-about-end>span{font-size:10px;font-weight:950;letter-spacing:.16em;color:#d58d60}.mc-about-hero h1{max-width:900px;font-size:clamp(46px,6.2vw,76px);line-height:.95;letter-spacing:-.07em;margin:17px 0 22px}.mc-about-hero p{max-width:760px;color:#c4d1ca;font-size:16px;line-height:1.7}.mc-about-section{padding:88px 0}.mc-about-section.soft{background:#f0f3ee}.mc-about-grid{display:grid;grid-template-columns:300px 1fr;gap:75px}.mc-about-grid span{font-size:11px;color:#c47745;font-weight:950}.mc-about-grid h2,.mc-about-end h2{font-size:42px;line-height:1;letter-spacing:-.06em;margin:10px 0}.mc-about-grid p,.mc-about-end p{color:#68766f;font-size:15px;line-height:1.8;margin:0}.mc-about-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.mc-about-cards article{padding:25px;background:#fff;border:1px solid #dfe4de;border-radius:20px}.mc-about-cards b{font-size:10px;color:#3f715d}.mc-about-cards h3{font-size:20px;line-height:1.08;letter-spacing:-.04em;margin:28px 0 9px}.mc-about-cards p{color:#6e7b75;font-size:11px;line-height:1.55}.mc-about-end{max-width:820px}.mc-about-end>a{display:inline-flex;margin-top:20px;min-height:48px;padding:0 17px;align-items:center;border-radius:11px;background:#162b24;color:#fff;font-size:11px;font-weight:950}@media(max-width:760px){.mc-about-grid,.mc-about-cards{grid-template-columns:1fr}.mc-about-hero{padding:60px 0}.mc-about-section{padding:65px 0}.mc-about-hero h1{font-size:47px}}
    `}</style>
  </main>;
}
