import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { isLocale, type Locale } from "@/lib/i18n";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  return { title: locale === "fr" ? "Politique de confidentialité" : "Privacy policy", robots: { index: true, follow: true } };
}

export default async function PrivacyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params;
  if (!isLocale(raw)) notFound();
  const fr = (raw as Locale) === "fr";
  return <article className="legal-page">
    <div className="legal-inner">
      <span className="legal-eyebrow">MyCoco · {fr ? "Québec, Canada" : "Quebec, Canada"}</span>
      <h1>{fr ? "Politique de confidentialité" : "Privacy policy"}</h1>
      <p className="legal-lead">{fr ? "La confiance des familles passe avant tout. Cette politique explique, en termes simples, quelles informations MyCoco peut recueillir, pourquoi, comment elles sont protégées et quels choix vous avez." : "Family trust comes first. This policy explains, in plain language, what information MyCoco may collect, why we use it, how we protect it and what choices you have."}</p>
      <section><h2>{fr ? "1. Les renseignements que nous pouvons recueillir" : "1. Information we may collect"}</h2><p>{fr ? "Pour une demande de garde, nous pouvons recueillir les renseignements nécessaires au service, notamment la ville ou le code postal, la tranche d’âge de l’enfant, le type de garde recherché et la date de début souhaitée. Si nous ajoutons un compte, des alertes ou des réservations, des coordonnées supplémentaires pourront être demandées avec une information claire au moment de la collecte." : "For a childcare request, we may collect information needed to provide the service, such as city or postal code, a child’s age range, the type of childcare sought and a desired start date. If we add accounts, alerts or bookings, additional contact details may be requested with clear notice at collection."}</p></section>
      <section><h2>{fr ? "2. Pourquoi nous les utilisons" : "2. Why we use it"}</h2><p>{fr ? "Nous utilisons les renseignements pour fournir les fonctions demandées, améliorer la recherche et le jumelage, prévenir les abus, assurer la sécurité, répondre aux demandes et respecter nos obligations légales. Nous ne vendons pas les renseignements personnels des familles." : "We use information to provide requested features, improve search and matching, prevent abuse, maintain security, respond to requests and meet legal obligations. We do not sell families’ personal information."}</p></section>
      <section><h2>{fr ? "3. Consentement et contrôle" : "3. Consent and control"}</h2><p>{fr ? "Nous cherchons à obtenir un consentement compréhensible lorsque la loi l’exige. La collecte est limitée à ce qui est nécessaire pour la finalité annoncée. Lorsque le consentement est la base applicable, vous pouvez le retirer sous réserve des conséquences qui vous seront expliquées." : "We seek meaningful consent where required by law. Collection is limited to what is necessary for the stated purpose. Where consent is the applicable basis, you may withdraw it subject to consequences that will be explained to you."}</p></section>
      <section><h2>{fr ? "4. Partage et fournisseurs" : "4. Sharing and service providers"}</h2><p>{fr ? "Nous pouvons utiliser des fournisseurs technologiques pour héberger ou traiter les données, uniquement dans le cadre des services nécessaires. Les accès doivent être limités au besoin de savoir et les fournisseurs doivent offrir des protections appropriées. Les données peuvent être traitées au Canada ou ailleurs selon les fournisseurs retenus; toute information requise à ce sujet sera présentée dans la politique applicable." : "We may use technology providers to host or process data only as needed to operate the service. Access should be limited on a need-to-know basis and providers must provide appropriate safeguards. Data may be processed in Canada or elsewhere depending on selected providers; required disclosures will be included in the applicable policy."}</p></section>
      <section><h2>{fr ? "5. Conservation et destruction" : "5. Retention and deletion"}</h2><p>{fr ? "Nous conservons les renseignements seulement aussi longtemps que nécessaire aux fins identifiées, aux besoins opérationnels légitimes ou pour respecter une obligation légale. Des règles de conservation et de suppression documentées seront appliquées avant la mise en production complète." : "We retain information only as long as necessary for identified purposes, legitimate operational needs or legal requirements. Documented retention and deletion rules will be implemented before full production launch."}</p></section>
      <section><h2>{fr ? "6. Sécurité" : "6. Security"}</h2><p>{fr ? "MyCoco applique une approche de sécurité par couches : chiffrement en transit, contrôles d’accès, validation des entrées, protection contre l’abus, en-têtes de sécurité, limitation des données recueillies et surveillance des risques. Les mesures sont adaptées à la sensibilité des renseignements." : "MyCoco uses a layered security approach: encryption in transit, access controls, input validation, abuse protection, security headers, data minimization and risk monitoring. Safeguards are designed according to the sensitivity of the information."}</p></section>
      <section><h2>{fr ? "7. Vos droits" : "7. Your rights"}</h2><p>{fr ? "Selon la loi applicable, vous pouvez notamment demander l’accès à vos renseignements, leur correction, et obtenir des explications sur leur utilisation. Vous pouvez aussi formuler une plainte ou une demande auprès de la personne responsable de la protection des renseignements personnels." : "Depending on applicable law, you may request access to your information, request corrections and obtain information about how it is used. You may also make a complaint or request to the person responsible for privacy at MyCoco."}</p></section>
      <section><h2>{fr ? "8. Cadre québécois et canadien" : "8. Quebec and Canadian framework"}</h2><p>{fr ? "MyCoco est conçu pour tenir compte des exigences applicables au Québec, notamment celles relatives à la protection des renseignements personnels dans le secteur privé, ainsi que des règles canadiennes applicables selon les activités. Cette page est une base produit et ne remplace pas une validation juridique." : "MyCoco is designed with Quebec private-sector privacy requirements and applicable Canadian rules in mind, depending on its activities. This page is a product foundation and does not replace legal review."}</p></section>
      <section className="legal-callout"><strong>{fr ? "Avant la mise en production" : "Before production launch"}</strong><p>{fr ? "Les coordonnées officielles de la personne responsable de la protection des renseignements personnels, la version finale des durées de conservation et la liste des sous-traitants pertinents doivent être complétées et validées juridiquement." : "The official privacy contact details, final retention periods and relevant processor list must be completed and legally reviewed."}</p></section>
      <p className="legal-date">{fr ? "Dernière mise à jour : septembre 2026" : "Last updated: September 2026"}</p>
    </div>
    <style>{`.legal-page{min-height:70vh;background:#f8f4ea;padding:72px 20px}.legal-inner{max-width:820px;margin:auto;background:#fff;border:1px solid #dfe7e2;border-radius:24px;padding:clamp(28px,5vw,58px);box-shadow:0 18px 55px rgba(23,63,58,.08)}.legal-eyebrow{color:#236b58;font-size:.72rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.legal-page h1{font-size:clamp(2.3rem,5vw,4rem);line-height:1.02;letter-spacing:-.055em;margin:14px 0 18px;color:#173f3a}.legal-lead{font-size:1.08rem;line-height:1.7;color:#315b53;margin-bottom:38px}.legal-page section{padding:24px 0;border-top:1px solid #edf1ee}.legal-page h2{font-size:1.08rem;margin:0 0 9px;color:#173f3a}.legal-page p{color:#5f706b;line-height:1.72;margin:0}.legal-callout{padding:18px!important;margin-top:20px;border:1px solid #d3e4da!important;border-radius:16px;background:#f0f6f2}.legal-callout strong{display:block;color:#236b58;margin-bottom:5px}.legal-date{font-size:.75rem;margin-top:26px!important;color:#71827d!important}.skip-link{position:fixed;left:12px;top:12px;transform:translateY(-150%);z-index:100;background:#173f3a;color:#fff;padding:10px 14px;border-radius:10px;font-weight:800}.skip-link:focus{transform:translateY(0)}`}</style>
  </article>;
}
