import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  const fr = locale === "fr";
  return { title: fr ? "Comment ça marche" : "How it works", description: fr ? "Comprendre simplement les parcours MyCoco pour les familles et les services de garde." : "Understand the MyCoco journeys for families and childcare providers." };
}

export default async function HowItWorks({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const fr = locale === "fr";
  return <main className="mc-how-page">
    <section className="mc-how-hero"><div><span>{fr ? "MYCOCO · COMMENT ÇA MARCHE" : "MYCOCO · HOW IT WORKS"}</span><h1>{fr ? "Deux parcours. Une même promesse : vous faire gagner du temps." : "Two journeys. One promise: save you time."}</h1><p>{fr ? "MyCoco est construit autour de deux utilisateurs. Les familles cherchent une solution. Les services veulent rencontrer les bonnes familles. La plateforme doit servir les deux sans compliquer l'expérience." : "MyCoco is built around two users. Families need a solution. Providers need the right families. The platform must serve both without adding friction."}</p></div></section>
    <section className="mc-how-body"><div className="mc-how-wrap">
      <article className="mc-how-card family"><div className="mc-how-label">01 · {fr ? "FAMILLE" : "FAMILY"}</div><h2>{fr ? "Je cherche une garde" : "I need childcare"}</h2><ol>{(fr ? [["Créer mon profil", "Quelques informations pour que MyCoco comprenne votre famille."],["Définir mon besoin", "Secteur, âge, type de garde et date souhaitée."],["Découvrir", "Des services pertinents, avec les informations qui comptent."],["Suivre", "Votre recherche reste active et peut évoluer avec votre famille."]] : [["Create my profile", "A few details so MyCoco understands your family."],["Define my need", "Area, age, childcare type and desired timing."],["Discover", "Relevant providers with the information that matters."],["Keep searching", "Your search stays active as your family changes."]]).map(([title,text],i)=><li key={title}><b>0{i+1}</b><div><strong>{title}</strong><p>{text}</p></div></li>)}</ol><Link href={`/${locale}/mon-besoin`}>{fr ? "Commencer ma recherche" : "Start my search"} →</Link></article>
      <article className="mc-how-card provider"><div className="mc-how-label">02 · {fr ? "SERVICE DE GARDE" : "PROVIDER"}</div><h2>{fr ? "Je veux être trouvé" : "I want to be discovered"}</h2><ol>{(fr ? [["Créer mon espace", "Présenter votre service et vos coordonnées."],["Compléter ma fiche", "Horaires, âges, capacité, tarifs, photos et particularités."],["Être visible", "Votre fiche devient une vraie vitrine locale."],["Convertir", "À terme : demandes qualifiées, leads et outils MyCoco Pro."]] : [["Create my space", "Present your service and contact details."],["Complete my page", "Hours, ages, capacity, pricing, photos and specifics."],["Get discovered", "Your page becomes a real local storefront."],["Convert", "Over time: qualified requests, leads and MyCoco Pro tools."]]).map(([title,text],i)=><li key={title}><b>0{i+1}</b><div><strong>{title}</strong><p>{text}</p></div></li>)}</ol><Link href={`/${locale}/pour-les-services`}>{fr ? "Créer mon espace service" : "Create my provider space"} →</Link></article>
    </div></section>
    <section className="mc-how-note"><div><span>{fr ? "IMPORTANT" : "IMPORTANT"}</span><h2>{fr ? "MyCoco aide à trouver. Le service confirme la place." : "MyCoco helps you discover. The provider confirms the spot."}</h2><p>{fr ? "Les informations affichées doivent être vérifiées auprès du service. MyCoco complète les démarches officielles du Québec et ne remplace pas les processus d'admission." : "Displayed information should be confirmed with the provider. MyCoco complements Quebec's official childcare process and does not replace admission procedures."}</p></div></section>
    <style>{`.mc-how-page{background:#fbfaf6;color:#162b24}.mc-how-hero{padding:88px 0 75px;background:#162b24;color:#fff}.mc-how-hero>div,.mc-how-wrap,.mc-how-note>div{width:min(1080px,calc(100% - 40px));margin:auto}.mc-how-hero span,.mc-how-label,.mc-how-note span{font-size:10px;font-weight:950;letter-spacing:.15em;color:#d58d60}.mc-how-hero h1{max-width:850px;font-size:clamp(45px,6vw,72px);line-height:.96;letter-spacing:-.07em;margin:16px 0 22px}.mc-how-hero p{max-width:760px;color:#c1d0c8;font-size:16px;line-height:1.7;margin:0}.mc-how-body{padding:65px 0}.mc-how-wrap{display:grid;grid-template-columns:1fr 1fr;gap:16px}.mc-how-card{padding:29px;border:1px solid #dfe4de;border-radius:22px;background:#fff}.mc-how-card.provider{background:#eee5dc}.mc-how-card h2{font-size:31px;letter-spacing:-.05em;margin:12px 0 25px}.mc-how-card ol{list-style:none;padding:0;margin:0 0 25px}.mc-how-card li{display:grid;grid-template-columns:32px 1fr;gap:10px;padding:15px 0;border-top:1px solid #e3e8e2}.mc-how-card li>b{font-size:10px;color:#7a9b89}.mc-how-card strong{font-size:13px}.mc-how-card p{color:#6f7b75;font-size:11px;line-height:1.5;margin:4px 0 0}.mc-how-card>a{font-size:11px;font-weight:950;color:#315e4e}.mc-how-note{padding:0 0 85px}.mc-how-note>div{padding:30px;background:#e7f0ea;border-radius:22px}.mc-how-note h2{font-size:30px;line-height:1.05;letter-spacing:-.045em;margin:12px 0}.mc-how-note p{max-width:760px;color:#61736a;font-size:12px;line-height:1.6;margin:0}@media(max-width:760px){.mc-how-wrap{grid-template-columns:1fr}.mc-how-hero{padding:60px 0}.mc-how-hero h1{font-size:46px}}
    `}</style>
  </main>;
}
