import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  return { title: locale === "fr" ? "Conditions d’utilisation" : "Terms of use" };
}

export default async function TermsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params;
  if (!isLocale(raw)) notFound();
  const fr = raw === "fr";
  return <article className="legal-page"><div className="legal-inner">
    <span className="legal-eyebrow">MyCoco · {fr ? "Conditions" : "Terms"}</span>
    <h1>{fr ? "Conditions d’utilisation" : "Terms of use"}</h1>
    <p className="legal-lead">{fr ? "MyCoco est une plateforme de découverte et de mise en relation. Ces conditions définissent le fonctionnement général du service et les responsabilités de chacun." : "MyCoco is a discovery and matching platform. These terms describe the general operation of the service and each party’s responsibilities."}</p>
    <section><h2>{fr ? "1. Rôle de MyCoco" : "1. MyCoco’s role"}</h2><p>{fr ? "MyCoco peut présenter des services de garde, des activités et d’autres solutions familiales. Sauf indication contraire, MyCoco n’est pas le fournisseur de garde et ne garantit ni une place, ni une disponibilité, ni l’acceptation d’une famille." : "MyCoco may present childcare, activities and other family solutions. Unless expressly stated otherwise, MyCoco is not the childcare provider and does not guarantee a space, availability or a family’s acceptance."}</p></section>
    <section><h2>{fr ? "2. Exactitude des informations" : "2. Information accuracy"}</h2><p>{fr ? "Les informations provenant de répertoires publics ou de fournisseurs peuvent changer. Nous faisons des efforts raisonnables pour présenter des informations utiles, mais les familles doivent confirmer les disponibilités, tarifs, horaires, conditions d’admission et autorisations directement auprès du fournisseur." : "Information from public directories or providers can change. We make reasonable efforts to provide useful information, but families should confirm availability, rates, hours, admission conditions and authorizations directly with the provider."}</p></section>
    <section><h2>{fr ? "3. Utilisation acceptable" : "3. Acceptable use"}</h2><p>{fr ? "Il est interdit d’utiliser MyCoco pour transmettre des renseignements faux, harceler un utilisateur, contourner les contrôles de sécurité, extraire massivement des données ou tenter d’accéder à des comptes ou systèmes sans autorisation." : "You may not use MyCoco to submit false information, harass users, bypass security controls, scrape data at scale or attempt to access accounts or systems without authorization."}</p></section>
    <section><h2>{fr ? "4. Fournisseurs et familles" : "4. Providers and families"}</h2><p>{fr ? "Les fournisseurs demeurent responsables de leurs services, de leurs obligations professionnelles, de leurs autorisations et de leurs communications avec les familles. Les familles demeurent responsables de vérifier qu’un service répond à leurs besoins et à ceux de leur enfant." : "Providers remain responsible for their services, professional obligations, authorizations and communications with families. Families remain responsible for confirming that a service meets their needs and those of their child."}</p></section>
    <section><h2>{fr ? "5. Évolution du service" : "5. Service changes"}</h2><p>{fr ? "MyCoco peut ajouter, modifier ou retirer des fonctionnalités. Les conditions applicables seront mises à jour lorsque nécessaire. Les changements importants seront présentés de façon raisonnable." : "MyCoco may add, modify or remove features. Applicable terms will be updated when necessary, with material changes communicated in a reasonable manner."}</p></section>
    <section><h2>{fr ? "6. Limitation" : "6. Limitations"}</h2><p>{fr ? "Dans la mesure permise par la loi, MyCoco ne garantit pas que le service sera toujours disponible, exempt d’erreurs ou qu’une recherche mènera à une place. Aucune disposition de ces conditions ne vise à exclure une responsabilité qui ne peut légalement être exclue." : "To the extent permitted by law, MyCoco does not guarantee uninterrupted or error-free service or that a search will result in a childcare space. Nothing in these terms excludes liability that cannot legally be excluded."}</p></section>
    <section className="legal-callout"><strong>{fr ? "Important" : "Important"}</strong><p>{fr ? "Ces conditions constituent une base produit et doivent faire l’objet d’une révision juridique au Québec avant la mise en production commerciale et la monétisation." : "These terms are a product foundation and should receive Quebec legal review before commercial production launch and monetization."}</p></section>
    <p className="legal-date">{fr ? "Dernière mise à jour : septembre 2026" : "Last updated: September 2026"}</p>
  </div><style>{`.legal-page{min-height:70vh;background:#f8f4ea;padding:72px 20px}.legal-inner{max-width:820px;margin:auto;background:#fff;border:1px solid #dfe7e2;border-radius:24px;padding:clamp(28px,5vw,58px);box-shadow:0 18px 55px rgba(23,63,58,.08)}.legal-eyebrow{color:#236b58;font-size:.72rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.legal-page h1{font-size:clamp(2.3rem,5vw,4rem);line-height:1.02;letter-spacing:-.055em;margin:14px 0 18px;color:#173f3a}.legal-lead{font-size:1.08rem;line-height:1.7;color:#315b53;margin-bottom:38px}.legal-page section{padding:24px 0;border-top:1px solid #edf1ee}.legal-page h2{font-size:1.08rem;margin:0 0 9px;color:#173f3a}.legal-page p{color:#5f706b;line-height:1.72;margin:0}.legal-callout{padding:18px!important;margin-top:20px;border:1px solid #d3e4da!important;border-radius:16px;background:#f0f6f2}.legal-callout strong{display:block;color:#236b58;margin-bottom:5px}.legal-date{font-size:.75rem;margin-top:26px!important;color:#71827d!important}`}</style>
  </article>;
}
