import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale, locales, type Locale } from "@/lib/i18n";
import NeedWizard from "@/components/NeedWizard";

export function generateStaticParams(){return locales.map(locale=>({locale}));}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const{locale:raw}=await params;if(!isLocale(raw))return{};const fr=raw==='fr';return{alternates:{canonical:`/${raw}/mon-besoin`,languages:{"fr-CA":"/fr/mon-besoin","en-CA":"/en/mon-besoin"}},title:fr?"Trouver ma garde | MyCoco":"Find my childcare | MyCoco",description:fr?"Décrivez le besoin de votre famille et découvrez les services de garde pertinents près de chez vous.":"Tell us what your family needs and discover relevant childcare services nearby."};}

export default async function MyNeedPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){const{locale:raw}=await params;const query=await searchParams;if(!isLocale(raw))notFound();const locale=raw as Locale;const fr=locale==='fr';const code=typeof query.erreur==='string'?query.erreur:'';const error=code?(fr?"Vérifiez les informations puis réessayez.":"Check the information and try again."):'';return <main className="mc-search-experience">
<section className="mc-search-hero"><div className="mc-home-container"><Link className="mc-back-link" href={`/${locale}`}>← {fr?"Retour à MyCoco":"Back to MyCoco"}</Link><div className="mc-search-hero-inner"><div><span className="mc-home-kicker">MYCOCO · {fr?"POUR LES FAMILLES":"FOR FAMILIES"}</span><h1>{fr?"Décrivez votre besoin. Nous faisons le tri avec vous.":"Tell us what you need. We’ll help narrow it down."}</h1><p>{fr?"Quelques questions pour comprendre votre secteur, l’âge de votre enfant, votre préférence et votre date de début.":"A few questions about your area, your child’s age, your preference and desired start date."}</p><div className="mc-search-promises"><span>✓ {fr?"Gratuit":"Free"}</span><span>✓ {fr?"Sans compte pour commencer":"No account to start"}</span><span>✓ {fr?"Environ 2 minutes":"About 2 minutes"}</span></div></div><div className="mc-search-journey-mini"><span>{fr?"VOTRE PARCOURS":"YOUR JOURNEY"}</span><div><b>01</b><strong>{fr?"Besoin":"Need"}</strong></div><div><b>02</b><strong>{fr?"Solutions":"Options"}</strong></div><div><b>03</b><strong>{fr?"Choix":"Choice"}</strong></div></div></div></div></section>
<section className="mc-search-content"><div className="mc-home-container mc-search-layout"><div><NeedWizard locale={locale} error={error}/></div><aside className="mc-search-side"><span className="mc-home-kicker">{fr?"POURQUOI CES QUESTIONS ?":"WHY THESE QUESTIONS?"}</span><h2>{fr?"Chaque réponse nous aide à mieux cibler votre recherche.":"Every answer helps narrow your search."}</h2><div className="mc-side-point"><b>01</b><p>{fr?"Le secteur permet de commencer près de chez vous.":"Your area keeps the search close to home."}</p></div><div className="mc-side-point"><b>02</b><p>{fr?"L’âge précise votre besoin. Confirmez les âges accueillis avec le service.":"Age clarifies your need. Confirm accepted ages with the provider."}</p></div><div className="mc-side-point"><b>03</b><p>{fr?"Votre préférence aide à classer les solutions.":"Your preference helps rank the options."}</p></div><div className="mc-side-point"><b>04</b><p>{fr?"La date donne un contexte à la recherche.":"Your start date adds context to the search."}</p></div><div className="mc-side-note"><strong>{fr?"Et après ?":"What happens next?"}</strong><p>{fr?"Consultez les fiches, vérifiez les coordonnées et contactez les services qui vous intéressent.":"Review profiles, check contact details and reach out to providers that interest you."}</p></div><p className="mc-search-legal">{fr?"MyCoco complète les démarches officielles du Québec. Une fiche ou un résultat ne garantit jamais une place disponible.":"MyCoco complements Quebec’s official process. A listing or result never guarantees an available spot."}</p></aside></div></section>
<section className="mc-search-end"><div className="mc-home-container"><span>{fr?"NOTRE PROMESSE":"OUR PROMISE"}</span><h2>{fr?"Moins de recherches. Plus de décisions utiles.":"Less searching. More useful decisions."}</h2></div></section>
</main>;
}
