import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {isLocale,type Locale,getDictionary,locales} from "@/lib/i18n";
import {cities,site} from "@/lib/site";
import Link from "next/link";
export function generateStaticParams(){return locales.map(locale=>({locale}))}
function copy(locale:Locale,slug:string[]){const d=getDictionary(locale);const fr=locale==="fr";const city=slug[0]==="garderie"&&slug[1]?cities.find(c=>c.slug===slug[1]):null;const title=city?(fr?`Garderies à ${city.name}`:`Daycares in ${city.name}`):slug[0]==="cpe"?d.pages.cpeTitle:slug[0]==="garderie-subventionnee"?d.pages.subsidizedTitle:slug[0]==="garderies"?d.pages.searchTitle:slug[0]==="a-propos"?d.pages.aboutTitle:slug[0]==="confidentialite"?d.pages.privacyTitle:slug[0]==="conditions"?d.pages.termsTitle:slug[0]==="temoins"?d.pages.cookiesTitle:null;return title?{title,description:city?(fr?`Trouvez des options de garde à ${city.name}.`:`Find childcare options in ${city.name}, Quebec.`):d.pages.searchDesc}:null}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug?:string[]}>}):Promise<Metadata>{const{locale:raw,slug=[]}=await params;if(!isLocale(raw))return{};const locale=raw as Locale;const c=copy(locale,slug);if(!c)return{};const suffix=`/${slug.join("/")}`;return{title:c.title,description:c.description,alternates:{canonical:`/${locale}${suffix}`,languages:{"fr-CA":`/fr${suffix}`,"en-CA":`/en${suffix}`,"x-default":`/fr${suffix}`}},openGraph:{title:c.title,description:c.description,locale:locale==="fr"?"fr_CA":"en_CA",siteName:site.name,type:"website"}}}
export default async function Page({params}:{params:Promise<{locale:string;slug?:string[]}>}){const{locale:raw,slug=[]}=await params;if(!isLocale(raw))notFound();const locale=raw as Locale;const d=getDictionary(locale);const fr=locale==="fr";if(!slug.length)return null;const c=copy(locale,slug);if(!c)notFound();return <section><div className="section-inner"><span className="eyebrow">{fr?"Québec":"Quebec"}</span><h1>{c.title}</h1><p>{c.description}</p>{!slug.includes("confidentialite")&&!slug.includes("conditions")&&!slug.includes("temoins")&&<Link className="button-link" href={`/${locale}/garderies`}>{d.home.search}</Link>}</div></section>}
